add_assoc_string(z_reason_texts, "0", "No reason to report.", 1);
add_assoc_string(z_reason_texts, "900", "Lowest value for an application-defined reason code returned by a data-conversion exit.", 1);
add_assoc_string(z_reason_texts, "999", "Highest value for application-defined reason code returned by a data-conversion exit.", 1);
add_assoc_string(z_reason_texts, "2001", "Alias base queue not a valid type.", 1);
add_assoc_string(z_reason_texts, "2002", "Application already connected.", 1);
add_assoc_string(z_reason_texts, "2003", "Unit of work encountered fatal error or backed out.", 1);
add_assoc_string(z_reason_texts, "2004", "Buffer parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2005", "Buffer length parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2006", "Length of character attributes not valid.", 1);
add_assoc_string(z_reason_texts, "2007", "Character attributes string not valid.", 1);
add_assoc_string(z_reason_texts, "2008", "Not enough space allowed for character attributes.", 1);
add_assoc_string(z_reason_texts, "2009", "Connection to queue manager lost.", 1);
add_assoc_string(z_reason_texts, "2010", "Data length parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2011", "Name of dynamic queue not valid.", 1);
add_assoc_string(z_reason_texts, "2012", "Call not valid in environment.", 1);
add_assoc_string(z_reason_texts, "2013", "Expiry time not valid.", 1);
add_assoc_string(z_reason_texts, "2014", "Feedback code not valid.", 1);
add_assoc_string(z_reason_texts, "2016", "Gets inhibited for the queue.", 1);
add_assoc_string(z_reason_texts, "2017", "No more handles available.", 1);
add_assoc_string(z_reason_texts, "2018", "Connection handle not valid.", 1);
add_assoc_string(z_reason_texts, "2019", "Object handle not valid.", 1);
add_assoc_string(z_reason_texts, "2020", "Value for inhibit-get or inhibit-put queue attribute not valid.", 1);
add_assoc_string(z_reason_texts, "2021", "Count of integer attributes not valid.", 1);
add_assoc_string(z_reason_texts, "2022", "Not enough space allowed for integer attributes.", 1);
add_assoc_string(z_reason_texts, "2023", "Integer attributes array not valid.", 1);
add_assoc_string(z_reason_texts, "2024", "No more messages can be handled within current unit of work.", 1);
add_assoc_string(z_reason_texts, "2025", "Maximum number of connections reached.", 1);
add_assoc_string(z_reason_texts, "2026", "Message descriptor not valid.", 1);
add_assoc_string(z_reason_texts, "2027", "Missing reply-to queue.", 1);
add_assoc_string(z_reason_texts, "2029", "Message type in message descriptor not valid.", 1);
add_assoc_string(z_reason_texts, "2030", "Message length greater than maximum for queue.", 1);
add_assoc_string(z_reason_texts, "2031", "Message length greater than maximum for queue manager.", 1);
add_assoc_string(z_reason_texts, "2033", "No message available.", 1);
add_assoc_string(z_reason_texts, "2034", "Browse cursor not positioned on message.", 1);
add_assoc_string(z_reason_texts, "2035", "Not authorized for access.", 1);
add_assoc_string(z_reason_texts, "2036", "Queue not open for browse.", 1);
add_assoc_string(z_reason_texts, "2037", "Queue not open for input.", 1);
add_assoc_string(z_reason_texts, "2038", "Queue not open for inquire.", 1);
add_assoc_string(z_reason_texts, "2039", "Queue not open for output.", 1);
add_assoc_string(z_reason_texts, "2040", "Queue not open for set.", 1);
add_assoc_string(z_reason_texts, "2041", "Object definition changed since opened.", 1);
add_assoc_string(z_reason_texts, "2042", "Object already open with conflicting options.", 1);
add_assoc_string(z_reason_texts, "2043", "Object type not valid.", 1);
add_assoc_string(z_reason_texts, "2044", "Object descriptor structure not valid.", 1);
add_assoc_string(z_reason_texts, "2045", "Option not valid for object type.", 1);
add_assoc_string(z_reason_texts, "2046", "Options not valid or not consistent.", 1);
add_assoc_string(z_reason_texts, "2047", "Persistence not valid.", 1);
add_assoc_string(z_reason_texts, "2048", "Message on a temporary dynamic queue cannot be persistent.", 1);
add_assoc_string(z_reason_texts, "2049", "Message Priority exceeds maximum value supported.", 1);
add_assoc_string(z_reason_texts, "2050", "Message priority not valid.", 1);
add_assoc_string(z_reason_texts, "2051", "Put calls inhibited for the queue.", 1);
add_assoc_string(z_reason_texts, "2052", "Queue has been deleted.", 1);
add_assoc_string(z_reason_texts, "2053", "Queue already contains maximum number of messages.", 1);
add_assoc_string(z_reason_texts, "2055", "Queue contains one or more messages or uncommitted put or get requests.", 1);
add_assoc_string(z_reason_texts, "2056", "No space available on disk for queue.", 1);
add_assoc_string(z_reason_texts, "2057", "Queue type not valid.", 1);
add_assoc_string(z_reason_texts, "2058", "Queue manager name not valid or not known.", 1);
add_assoc_string(z_reason_texts, "2059", "Queue manager not available for connection.", 1);
add_assoc_string(z_reason_texts, "2061", "Report options in message descriptor not valid.", 1);
add_assoc_string(z_reason_texts, "2062", "A message is already marked.", 1);
add_assoc_string(z_reason_texts, "2063", "Security error occurred.", 1);
add_assoc_string(z_reason_texts, "2065", "Count of selectors not valid.", 1);
add_assoc_string(z_reason_texts, "2066", "Count of selectors too big.", 1);
add_assoc_string(z_reason_texts, "2067", "Attribute selector not valid.", 1);
add_assoc_string(z_reason_texts, "2068", "Selector not applicable to queue type.", 1);
add_assoc_string(z_reason_texts, "2069", "Signal outstanding for this handle.", 1);
add_assoc_string(z_reason_texts, "2070", "No message returned (but signal request accepted).", 1);
add_assoc_string(z_reason_texts, "2071", "Insufficient storage available.", 1);
add_assoc_string(z_reason_texts, "2072", "Syncpoint support not available.", 1);
add_assoc_string(z_reason_texts, "2075", "Value for trigger-control attribute not valid.", 1);
add_assoc_string(z_reason_texts, "2076", "Value for trigger-depth attribute not valid.", 1);
add_assoc_string(z_reason_texts, "2077", "Value for trigger-message-priority attribute not valid.", 1);
add_assoc_string(z_reason_texts, "2078", "Value for trigger-type attribute not valid.", 1);
add_assoc_string(z_reason_texts, "2079", "Truncated message returned (processing completed).", 1);
add_assoc_string(z_reason_texts, "2080", "Truncated message returned (processing not completed).", 1);
add_assoc_string(z_reason_texts, "2082", "Unknown alias base queue.", 1);
add_assoc_string(z_reason_texts, "2085", "Unknown object name.", 1);
add_assoc_string(z_reason_texts, "2086", "Unknown object queue manager.", 1);
add_assoc_string(z_reason_texts, "2087", "Unknown remote queue manager.", 1);
add_assoc_string(z_reason_texts, "2090", "Wait interval in MQGMO not valid.", 1);
add_assoc_string(z_reason_texts, "2091", "Transmission queue not local.", 1);
add_assoc_string(z_reason_texts, "2092", "Transmission queue with wrong usage.", 1);
add_assoc_string(z_reason_texts, "2093", "Queue not open for pass all context.", 1);
add_assoc_string(z_reason_texts, "2094", "Queue not open for pass identity context.", 1);
add_assoc_string(z_reason_texts, "2095", "Queue not open for set all context.", 1);
add_assoc_string(z_reason_texts, "2096", "Queue not open for set identity context.", 1);
add_assoc_string(z_reason_texts, "2097", "Queue handle referred to does not save context.", 1);
add_assoc_string(z_reason_texts, "2098", "Context not available for queue handle referred to.", 1);
add_assoc_string(z_reason_texts, "2099", "Signal field not valid.", 1);
add_assoc_string(z_reason_texts, "2100", "Object already exists.", 1);
add_assoc_string(z_reason_texts, "2101", "Object damaged.", 1);
add_assoc_string(z_reason_texts, "2102", "Insufficient system resources available.", 1);
add_assoc_string(z_reason_texts, "2103", "Another queue manager already connected.", 1);
add_assoc_string(z_reason_texts, "2104", "Report option(s) in message descriptor not recognized.", 1);
add_assoc_string(z_reason_texts, "2105", "Storage class error.", 1);
add_assoc_string(z_reason_texts, "2106", "COD report option not valid for XCF queue.", 1);
add_assoc_string(z_reason_texts, "2107", "MQXWAIT call canceled.", 1);
add_assoc_string(z_reason_texts, "2108", "Invocation of MQXWAIT call not valid.", 1);
add_assoc_string(z_reason_texts, "2109", "Call suppressed by exit program.", 1);
add_assoc_string(z_reason_texts, "2110", "Message format not valid.", 1);
add_assoc_string(z_reason_texts, "2111", "Source coded character set identifier not valid.", 1);
add_assoc_string(z_reason_texts, "2112", "Source integer encoding not recognized.", 1);
add_assoc_string(z_reason_texts, "2113", "Packed-decimal encoding in message not recognized.", 1);
add_assoc_string(z_reason_texts, "2114", "Floating-point encoding in message not recognized.", 1);
add_assoc_string(z_reason_texts, "2115", "Target coded character set identifier not valid.", 1);
add_assoc_string(z_reason_texts, "2116", "Target integer encoding not recognized.", 1);
add_assoc_string(z_reason_texts, "2117", "Packed-decimal encoding specified by receiver not recognized.", 1);
add_assoc_string(z_reason_texts, "2118", "Floating-point encoding specified by receiver not recognized.", 1);
add_assoc_string(z_reason_texts, "2119", "Application message data not converted.", 1);
add_assoc_string(z_reason_texts, "2120", "Converted data too big for buffer.", 1);
add_assoc_string(z_reason_texts, "2121", "No participating resource managers registered.", 1);
add_assoc_string(z_reason_texts, "2122", "Participating resource manager not available.", 1);
add_assoc_string(z_reason_texts, "2123", "Result of commit or back-out operation is mixed.", 1);
add_assoc_string(z_reason_texts, "2124", "Result of commit operation is pending.", 1);
add_assoc_string(z_reason_texts, "2125", "Bridge started.", 1);
add_assoc_string(z_reason_texts, "2126", "Bridge stopped.", 1);
add_assoc_string(z_reason_texts, "2127", "Insufficient storage for adapter.", 1);
add_assoc_string(z_reason_texts, "2128", "Unit of work already started.", 1);
add_assoc_string(z_reason_texts, "2129", "Unable to load adapter connection module.", 1);
add_assoc_string(z_reason_texts, "2130", "Unable to load adapter service module.", 1);
add_assoc_string(z_reason_texts, "2131", "Adapter subsystem definition module not valid.", 1);
add_assoc_string(z_reason_texts, "2132", "Unable to load adapter subsystem definition module.", 1);
add_assoc_string(z_reason_texts, "2133", "Unable to load data conversion services modules.", 1);
add_assoc_string(z_reason_texts, "2134", "Begin-options structure not valid.", 1);
add_assoc_string(z_reason_texts, "2135", "Distribution header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2136", "Multiple reason codes returned.", 1);
add_assoc_string(z_reason_texts, "2137", "Object not opened successfully.", 1);
add_assoc_string(z_reason_texts, "2138", "Unable to load adapter disconnection module.", 1);
add_assoc_string(z_reason_texts, "2139", "Connect-options structure not valid.", 1);
add_assoc_string(z_reason_texts, "2140", "Wait request rejected by CICS.", 1);
add_assoc_string(z_reason_texts, "2141", "Dead letter header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2142", "MQ header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2143", "Source length parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2144", "Target length parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2145", "Source buffer parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2146", "Target buffer parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2148", "IMS information header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2149", "PCF structures not valid.", 1);
add_assoc_string(z_reason_texts, "2150", "DBCS string not valid.", 1);
add_assoc_string(z_reason_texts, "2152", "Object name not valid.", 1);
add_assoc_string(z_reason_texts, "2153", "Object queue-manager name not valid.", 1);
add_assoc_string(z_reason_texts, "2154", "Number of records present not valid.", 1);
add_assoc_string(z_reason_texts, "2155", "Object records not valid.", 1);
add_assoc_string(z_reason_texts, "2156", "Response records not valid.", 1);
add_assoc_string(z_reason_texts, "2157", "Primary and home ASIDs differ.", 1);
add_assoc_string(z_reason_texts, "2158", "Put message record flags not valid.", 1);
add_assoc_string(z_reason_texts, "2159", "Put message records not valid.", 1);
add_assoc_string(z_reason_texts, "2160", "Connection identifier already in use.", 1);
add_assoc_string(z_reason_texts, "2161", "Queue manager quiescing.", 1);
add_assoc_string(z_reason_texts, "2162", "Queue manager shutting down.", 1);
add_assoc_string(z_reason_texts, "2163", "Recovery coordinator already exists.", 1);
add_assoc_string(z_reason_texts, "2173", "Put-message options structure not valid.", 1);
add_assoc_string(z_reason_texts, "2183", "Unable to load API crossing exit.", 1);
add_assoc_string(z_reason_texts, "2184", "Remote queue name not valid.", 1);
add_assoc_string(z_reason_texts, "2185", "Inconsistent persistence specification.", 1);
add_assoc_string(z_reason_texts, "2186", "Get-message options structure not valid.", 1);
add_assoc_string(z_reason_texts, "2187", "Requested function not supported by CICS bridge.", 1);
add_assoc_string(z_reason_texts, "2188", "Call rejected by cluster-workload exit.", 1);
add_assoc_string(z_reason_texts, "2189", "Cluster name resolution failed.", 1);
add_assoc_string(z_reason_texts, "2190", "Converted string too big for field.", 1);
add_assoc_string(z_reason_texts, "2191", "Character trigger message structure not valid.", 1);
add_assoc_string(z_reason_texts, "2192", "Page set data set full.", 1);
add_assoc_string(z_reason_texts, "2193", "Error accessing page set data set.", 1);
add_assoc_string(z_reason_texts, "2194", "Object name not valid for object type.", 1);
add_assoc_string(z_reason_texts, "2195", "Unexpected error occurred.", 1);
add_assoc_string(z_reason_texts, "2196", "Unknown transmission queue.", 1);
add_assoc_string(z_reason_texts, "2197", "Unknown default transmission queue.", 1);
add_assoc_string(z_reason_texts, "2198", "Default transmission queue not local.", 1);
add_assoc_string(z_reason_texts, "2199", "Default transmission queue usage error.", 1);
add_assoc_string(z_reason_texts, "2201", "Name in use.", 1);
add_assoc_string(z_reason_texts, "2202", "Connection quiescing.", 1);
add_assoc_string(z_reason_texts, "2203", "Connection shutting down.", 1);
add_assoc_string(z_reason_texts, "2204", "Adapter not available.", 1);
add_assoc_string(z_reason_texts, "2206", "Message-identifier error.", 1);
add_assoc_string(z_reason_texts, "2207", "Correlation-identifier error.", 1);
add_assoc_string(z_reason_texts, "2208", "File-system error.", 1);
add_assoc_string(z_reason_texts, "2209", "No message locked.", 1);
add_assoc_string(z_reason_texts, "2217", "Not authorized for connection.", 1);
add_assoc_string(z_reason_texts, "2218", "Message length greater than maximum for channel.", 1);
add_assoc_string(z_reason_texts, "2219", "MQI call reentered before previous call complete.", 1);
add_assoc_string(z_reason_texts, "2220", "Reference message header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2222", "Queue manager created.", 1);
add_assoc_string(z_reason_texts, "2223", "Queue manager unavailable.", 1);
add_assoc_string(z_reason_texts, "2224", "Queue depth high limit reached or exceeded.", 1);
add_assoc_string(z_reason_texts, "2225", "Queue depth low limit reached or exceeded.", 1);
add_assoc_string(z_reason_texts, "2226", "Queue service interval high.", 1);
add_assoc_string(z_reason_texts, "2227", "Queue service interval ok.", 1);
add_assoc_string(z_reason_texts, "2232", "Unit of work not started.", 1);
add_assoc_string(z_reason_texts, "2233", "Automatic channel definition succeeded.", 1);
add_assoc_string(z_reason_texts, "2234", "Automatic channel definition failed.", 1);
add_assoc_string(z_reason_texts, "2235", "PCF header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2236", "PCF integer list parameter structure not valid.", 1);
add_assoc_string(z_reason_texts, "2237", "PCF integer parameter structure not valid.", 1);
add_assoc_string(z_reason_texts, "2238", "PCF string list parameter structure not valid.", 1);
add_assoc_string(z_reason_texts, "2239", "PCF string parameter structure not valid.", 1);
add_assoc_string(z_reason_texts, "2241", "Message group not complete.", 1);
add_assoc_string(z_reason_texts, "2242", "Logical message not complete.", 1);
add_assoc_string(z_reason_texts, "2243", "Message segments have differing CCSIDs.", 1);
add_assoc_string(z_reason_texts, "2244", "Message segments have differing encodings.", 1);
add_assoc_string(z_reason_texts, "2245", "Inconsistent unit-of-work specification.", 1);
add_assoc_string(z_reason_texts, "2246", "Message under cursor not valid for retrieval.", 1);
add_assoc_string(z_reason_texts, "2247", "Match options not valid.", 1);
add_assoc_string(z_reason_texts, "2248", "Message descriptor extension not valid.", 1);
add_assoc_string(z_reason_texts, "2249", "Message flags not valid.", 1);
add_assoc_string(z_reason_texts, "2250", "Message sequence number not valid.", 1);
add_assoc_string(z_reason_texts, "2251", "Message segment offset not valid.", 1);
add_assoc_string(z_reason_texts, "2252", "Original length not valid.", 1);
add_assoc_string(z_reason_texts, "2253", "Length of data in message segment is zero.", 1);
add_assoc_string(z_reason_texts, "2255", "Unit of work not available for the queue manager to use.", 1);
add_assoc_string(z_reason_texts, "2256", "Wrong version of MQGMO supplied.", 1);
add_assoc_string(z_reason_texts, "2257", "Wrong version of MQMD supplied.", 1);
add_assoc_string(z_reason_texts, "2258", "Group identifier not valid.", 1);
add_assoc_string(z_reason_texts, "2259", "Inconsistent browse specification.", 1);
add_assoc_string(z_reason_texts, "2260", "Transmission queue header structure not valid.", 1);
add_assoc_string(z_reason_texts, "2261", "Source environment data error.", 1);
add_assoc_string(z_reason_texts, "2262", "Source name data error.", 1);
add_assoc_string(z_reason_texts, "2263", "Destination environment data error.", 1);
add_assoc_string(z_reason_texts, "2264", "Destination name data error.", 1);
add_assoc_string(z_reason_texts, "2265", "Trigger message structure not valid.", 1);
add_assoc_string(z_reason_texts, "2266", "Cluster workload exit failed.", 1);
add_assoc_string(z_reason_texts, "2267", "Unable to load cluster workload exit.", 1);
add_assoc_string(z_reason_texts, "2268", "Put calls inhibited for all queues in cluster.", 1);
add_assoc_string(z_reason_texts, "2270", "No destination queues available.", 1);
add_assoc_string(z_reason_texts, "2273", "Error processing MQCONN call.", 1);
add_assoc_string(z_reason_texts, "2274", "Option not valid in environment.", 1);
add_assoc_string(z_reason_texts, "2277", "Channel definition not valid.", 1);
add_assoc_string(z_reason_texts, "2278", "Client connection fields not valid.", 1);
add_assoc_string(z_reason_texts, "2279", "Channel stopped by user.", 1);
add_assoc_string(z_reason_texts, "2280", "Configuration handle not valid.", 1);
add_assoc_string(z_reason_texts, "2281", "Function identifier not valid for service.", 1);
add_assoc_string(z_reason_texts, "2282", "Channel started.", 1);
add_assoc_string(z_reason_texts, "2283", "Channel stopped.", 1);
add_assoc_string(z_reason_texts, "2284", "Channel conversion error.", 1);
add_assoc_string(z_reason_texts, "2285", "Underlying service not available.", 1);
add_assoc_string(z_reason_texts, "2286", "Initialization failed for an undefined reason.", 1);
add_assoc_string(z_reason_texts, "2287", "Termination failed for an undefined reason.", 1);
add_assoc_string(z_reason_texts, "2288", "Queue name not found.", 1);
add_assoc_string(z_reason_texts, "2289", "Unexpected error occurred accessing service.", 1);
add_assoc_string(z_reason_texts, "2290", "Queue object already exists.", 1);
add_assoc_string(z_reason_texts, "2291", "Unable to determine the user ID.", 1);
add_assoc_string(z_reason_texts, "2292", "Entity unknown to service.", 1);
add_assoc_string(z_reason_texts, "2293", "Authorization entity unknown to service.", 1);
add_assoc_string(z_reason_texts, "2294", "Reference object unknown.", 1);
add_assoc_string(z_reason_texts, "2295", "Channel activated.", 1);
add_assoc_string(z_reason_texts, "2296", "Channel cannot be activated.", 1);
add_assoc_string(z_reason_texts, "2297", "Unit of work canceled.", 1);
add_assoc_string(z_reason_texts, "2299", "Selector has wrong data type.", 1);
add_assoc_string(z_reason_texts, "2300", "Command type not valid.", 1);
add_assoc_string(z_reason_texts, "2301", "Multiple instances of system data item not valid.", 1);
add_assoc_string(z_reason_texts, "2302", "System data item is read-only and cannot be altered.", 1);
add_assoc_string(z_reason_texts, "2303", "Data could not be converted into a bag.", 1);
add_assoc_string(z_reason_texts, "2304", "Selector not within valid range for call.", 1);
add_assoc_string(z_reason_texts, "2305", "Selector occurs more than once in bag.", 1);
add_assoc_string(z_reason_texts, "2306", "Index not present.", 1);
add_assoc_string(z_reason_texts, "2307", "String parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2308", "Encoding not supported.", 1);
add_assoc_string(z_reason_texts, "2309", "Selector not present in bag.", 1);
add_assoc_string(z_reason_texts, "2310", "OutSelector parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2311", "String truncated (too long for output buffer).", 1);
add_assoc_string(z_reason_texts, "2312", "Selector implies a data type not valid for call.", 1);
add_assoc_string(z_reason_texts, "2313", "Data type of item differs from previous occurrence of selector.", 1);
add_assoc_string(z_reason_texts, "2314", "Index not valid.", 1);
add_assoc_string(z_reason_texts, "2315", "System bag is read-only and cannot be altered.", 1);
add_assoc_string(z_reason_texts, "2316", "ItemCount parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2317", "Format not supported.", 1);
add_assoc_string(z_reason_texts, "2318", "System selector not supported.", 1);
add_assoc_string(z_reason_texts, "2319", "ItemValue parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2320", "Bag handle not valid.", 1);
add_assoc_string(z_reason_texts, "2321", "Parameter missing.", 1);
add_assoc_string(z_reason_texts, "2322", "Command server not available.", 1);
add_assoc_string(z_reason_texts, "2323", "StringLength parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2324", "Command code is not a recognized inquiry command.", 1);
add_assoc_string(z_reason_texts, "2325", "Input bag contains one or more nested bags.", 1);
add_assoc_string(z_reason_texts, "2326", "Bag has wrong type for intended use.", 1);
add_assoc_string(z_reason_texts, "2327", "ItemType parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2328", "System bag is read-only and cannot be deleted.", 1);
add_assoc_string(z_reason_texts, "2329", "System data item is read-only and cannot be deleted.", 1);
add_assoc_string(z_reason_texts, "2330", "Coded character set identifier parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2331", "Use of message token not valid.", 1);
add_assoc_string(z_reason_texts, "2332", "Message data does not begin with MQWIH.", 1);
add_assoc_string(z_reason_texts, "2333", "MQWIH structure not valid.", 1);
add_assoc_string(z_reason_texts, "2334", "MQRFH structure not valid.", 1);
add_assoc_string(z_reason_texts, "2335", "NameValueString field not valid.", 1);
add_assoc_string(z_reason_texts, "2336", "Command not valid.", 1);
add_assoc_string(z_reason_texts, "2337", "Parameter not valid.", 1);
add_assoc_string(z_reason_texts, "2338", "Duplicate parameter.", 1);
add_assoc_string(z_reason_texts, "2339", "Parameter missing.", 1);
add_assoc_string(z_reason_texts, "2367", "Create Object", 1);
add_assoc_string(z_reason_texts, "2368", "Change Object", 1);
add_assoc_string(z_reason_texts, "2369", "Delete Object", 1);
add_assoc_string(z_reason_texts, "2370", "Refresh Object", 1);
add_assoc_string(z_reason_texts, "3001", "Type not valid.", 1);
add_assoc_string(z_reason_texts, "3002", "Structure length not valid.", 1);
add_assoc_string(z_reason_texts, "3003", "Structure version number is not valid.", 1);
add_assoc_string(z_reason_texts, "3004", "Message sequence number not valid.", 1);
add_assoc_string(z_reason_texts, "3005", "Control option not valid.", 1);
add_assoc_string(z_reason_texts, "3006", "Parameter count not valid.", 1);
add_assoc_string(z_reason_texts, "3007", "Command identifier not valid.", 1);
add_assoc_string(z_reason_texts, "3008", "Command failed.", 1);
add_assoc_string(z_reason_texts, "3009", "Structure length not valid.", 1);
add_assoc_string(z_reason_texts, "3010", "Structure length not valid.", 1);
add_assoc_string(z_reason_texts, "3011", "String length not valid.", 1);
add_assoc_string(z_reason_texts, "3012", "Force value not valid.", 1);
add_assoc_string(z_reason_texts, "3013", "Structure type not valid.", 1);
add_assoc_string(z_reason_texts, "3014", "Parameter identifier is not valid.", 1);
add_assoc_string(z_reason_texts, "3015", "Parameter identifier is not valid.", 1);
add_assoc_string(z_reason_texts, "3016", "Message length not valid.", 1);
add_assoc_string(z_reason_texts, "3017", "Duplicate parameter.", 1);
add_assoc_string(z_reason_texts, "3018", "Duplicate parameter.", 1);
add_assoc_string(z_reason_texts, "3019", "Parameter count too small.", 1);
add_assoc_string(z_reason_texts, "3020", "Parameter count too big.", 1);
add_assoc_string(z_reason_texts, "3021", "Queue already exists in cell.", 1);
add_assoc_string(z_reason_texts, "3022", "Queue type not valid.", 1);
add_assoc_string(z_reason_texts, "3023", "Format not valid.", 1);
add_assoc_string(z_reason_texts, "3025", "Replace value not valid.", 1);
add_assoc_string(z_reason_texts, "3026", "Duplicate parameter.", 1);
add_assoc_string(z_reason_texts, "3027", "Count of parameter values not valid.", 1);
add_assoc_string(z_reason_texts, "3028", "Structure length not valid.", 1);
add_assoc_string(z_reason_texts, "3029", "Mode value not valid.", 1);
add_assoc_string(z_reason_texts, "3029", "Quiesce value not valid.", 1);
add_assoc_string(z_reason_texts, "3030", "Message sequence number not valid.", 1);
add_assoc_string(z_reason_texts, "3031", "Data count not valid.", 1);
add_assoc_string(z_reason_texts, "3032", "Ping Channel command failed.", 1);
add_assoc_string(z_reason_texts, "3034", "Channel type not valid.", 1);
add_assoc_string(z_reason_texts, "3035", "Parameter sequence not valid.", 1);
add_assoc_string(z_reason_texts, "3036", "Transmission protocol type not valid.", 1);
add_assoc_string(z_reason_texts, "3037", "Batch size not valid.", 1);
add_assoc_string(z_reason_texts, "3038", "Disconnection interval not valid.", 1);
add_assoc_string(z_reason_texts, "3039", "Short retry count not valid.", 1);
add_assoc_string(z_reason_texts, "3040", "Short timer value not valid.", 1);
add_assoc_string(z_reason_texts, "3041", "Long retry count not valid.", 1);
add_assoc_string(z_reason_texts, "3042", "Long timer not valid.", 1);
add_assoc_string(z_reason_texts, "3043", "Sequence wrap number not valid.", 1);
add_assoc_string(z_reason_texts, "3044", "Maximum message length not valid.", 1);
add_assoc_string(z_reason_texts, "3045", "Put authority value not valid.", 1);
add_assoc_string(z_reason_texts, "3046", "Purge value not valid.", 1);
add_assoc_string(z_reason_texts, "3047", "Parameter identifier is not valid.", 1);
add_assoc_string(z_reason_texts, "3048", "Message truncated.", 1);
add_assoc_string(z_reason_texts, "3049", "Coded character-set identifier error.", 1);
add_assoc_string(z_reason_texts, "3050", "Encoding error.", 1);
add_assoc_string(z_reason_texts, "3052", "Data conversion value not valid.", 1);
add_assoc_string(z_reason_texts, "3053", "In-doubt value not valid.", 1);
add_assoc_string(z_reason_texts, "3054", "Escape type not valid.", 1);
add_assoc_string(z_reason_texts, "3062", "Channel table value not valid.", 1);
add_assoc_string(z_reason_texts, "3063", "Message channel agent type not valid.", 1);
add_assoc_string(z_reason_texts, "3064", "Channel instance type not valid.", 1);
add_assoc_string(z_reason_texts, "3065", "Channel status not found.", 1);
add_assoc_string(z_reason_texts, "3066", "Duplicate parameter.", 1);
add_assoc_string(z_reason_texts, "3067", "Total string length error.", 1);
add_assoc_string(z_reason_texts, "3068", "Name count value not valid.", 1);
add_assoc_string(z_reason_texts, "3069", "String length not valid.", 1);
add_assoc_string(z_reason_texts, "3086", "Queue manager coded character set identifier error.", 1);
add_assoc_string(z_reason_texts, "3088", "ClusterName and ClusterNamelist attributes conflict.", 1);
add_assoc_string(z_reason_texts, "3089", "RepositoryName and RepositoryNamelist attributes conflict.", 1);
add_assoc_string(z_reason_texts, "3090", "Cluster queue cannot be a transmission queue.", 1);
add_assoc_string(z_reason_texts, "3091", "Action value not valid.", 1);
add_assoc_string(z_reason_texts, "3092", "Library for requested communications protocol could not be loaded.", 1);
add_assoc_string(z_reason_texts, "3093", "NetBIOS listener name not defined.", 1);
add_assoc_string(z_reason_texts, "3095", "Conflicting parameters.", 1);
add_assoc_string(z_reason_texts, "3150", "Content based filter expression not valid.", 1);
add_assoc_string(z_reason_texts, "3151", "Wrong user.", 1);
add_assoc_string(z_reason_texts, "4001", "Object already exists.", 1);
add_assoc_string(z_reason_texts, "4002", "Object has wrong type.", 1);
add_assoc_string(z_reason_texts, "4003", "New and existing objects have different type.", 1);
add_assoc_string(z_reason_texts, "4004", "Object is open.", 1);
add_assoc_string(z_reason_texts, "4005", "Attribute value not valid.", 1);
add_assoc_string(z_reason_texts, "4006", "Queue manager not known.", 1);
add_assoc_string(z_reason_texts, "4007", "Action not valid for the queue of specified type.", 1);
add_assoc_string(z_reason_texts, "4008", "Object name not valid.", 1);
add_assoc_string(z_reason_texts, "4009", "Allocation failed.", 1);
add_assoc_string(z_reason_texts, "4010", "Remote system not available.", 1);
add_assoc_string(z_reason_texts, "4011", "Configuration error.", 1);
add_assoc_string(z_reason_texts, "4012", "Connection refused.", 1);
add_assoc_string(z_reason_texts, "4013", "Invalid connection name.", 1);
add_assoc_string(z_reason_texts, "4014", "Send failed.", 1);
add_assoc_string(z_reason_texts, "4015", "Received data error.", 1);
add_assoc_string(z_reason_texts, "4016", "Receive failed.", 1);
add_assoc_string(z_reason_texts, "4017", "Connection closed.", 1);
add_assoc_string(z_reason_texts, "4018", "Not enough storage available.", 1);
add_assoc_string(z_reason_texts, "4019", "Communications manager not available.", 1);
add_assoc_string(z_reason_texts, "4020", "Listener not started.", 1);
add_assoc_string(z_reason_texts, "4024", "Bind failed.", 1);
add_assoc_string(z_reason_texts, "4025", "Channel in-doubt.", 1);
add_assoc_string(z_reason_texts, "4026", "MQCONN call failed.", 1);
add_assoc_string(z_reason_texts, "4027", "MQOPEN call failed.", 1);
add_assoc_string(z_reason_texts, "4028", "MQGET call failed.", 1);
add_assoc_string(z_reason_texts, "4029", "MQPUT call failed.", 1);
add_assoc_string(z_reason_texts, "4030", "Ping error.", 1);
add_assoc_string(z_reason_texts, "4031", "Channel in use.", 1);
add_assoc_string(z_reason_texts, "4032", "Channel not found.", 1);
add_assoc_string(z_reason_texts, "4033", "Remote channel not known.", 1);
add_assoc_string(z_reason_texts, "4034", "Remote queue manager not available.", 1);
add_assoc_string(z_reason_texts, "4035", "Remote queue manager terminating.", 1);
add_assoc_string(z_reason_texts, "4036", "MQINQ call failed.", 1);
add_assoc_string(z_reason_texts, "4037", "Queue is not a transmission queue.", 1);
add_assoc_string(z_reason_texts, "4038", "Channel disabled.", 1);
add_assoc_string(z_reason_texts, "4039", "User exit not available.", 1);
add_assoc_string(z_reason_texts, "4040", "Commit failed.", 1);
add_assoc_string(z_reason_texts, "4041", "Parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4042", "Channel already exists.", 1);
add_assoc_string(z_reason_texts, "4043", "Data too large.", 1);
add_assoc_string(z_reason_texts, "4044", "Channel name error.", 1);
add_assoc_string(z_reason_texts, "4045", "Transmission queue name error.", 1);
add_assoc_string(z_reason_texts, "4047", "Message channel agent name error.", 1);
add_assoc_string(z_reason_texts, "4048", "Channel send exit name error.", 1);
add_assoc_string(z_reason_texts, "4049", "Channel security exit name error.", 1);
add_assoc_string(z_reason_texts, "4050", "Channel message exit name error.", 1);
add_assoc_string(z_reason_texts, "4051", "Channel receive exit name error.", 1);
add_assoc_string(z_reason_texts, "4052", "Transmission queue name not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4053", "Message channel agent name not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4054", "Disconnection interval not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4055", "Short retry parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4056", "Short timer parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4057", "Long retry parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4058", "Long timer parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4059", "Put authority parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4060", "Keepalive interval not valid.", 1);
add_assoc_string(z_reason_texts, "4061", "Connection name parameter required but missing.", 1);
add_assoc_string(z_reason_texts, "4062", "Error in connection name parameter.", 1);
add_assoc_string(z_reason_texts, "4063", "MQSET call failed.", 1);
add_assoc_string(z_reason_texts, "4064", "Channel not active.", 1);
add_assoc_string(z_reason_texts, "4065", "Channel terminated by security exit.", 1);
add_assoc_string(z_reason_texts, "4067", "Dynamic queue scope error.", 1);
add_assoc_string(z_reason_texts, "4068", "Cell directory is not available.", 1);
add_assoc_string(z_reason_texts, "4069", "Message retry count not valid.", 1);
add_assoc_string(z_reason_texts, "4070", "Message-retry count parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4071", "Channel message-retry exit name error.", 1);
add_assoc_string(z_reason_texts, "4072", "Message-retry exit parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4073", "Message retry interval not valid.", 1);
add_assoc_string(z_reason_texts, "4074", "Message-retry interval parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4075", "Nonpersistent message speed not valid.", 1);
add_assoc_string(z_reason_texts, "4076", "Nonpersistent message speed parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4077", "Heartbeat interval not valid.", 1);
add_assoc_string(z_reason_texts, "4078", "Heartbeat interval parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4079", "Channel automatic definition error.", 1);
add_assoc_string(z_reason_texts, "4080", "Channel automatic definition parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4081", "Channel automatic definition event error.", 1);
add_assoc_string(z_reason_texts, "4082", "Channel automatic definition event parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4083", "Channel automatic definition exit name error.", 1);
add_assoc_string(z_reason_texts, "4084", "Channel automatic definition exit parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4085", "Action suppressed by exit program.", 1);
add_assoc_string(z_reason_texts, "4086", "Batch interval not valid.", 1);
add_assoc_string(z_reason_texts, "4087", "Batch interval parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "4088", "Network priority value is not valid.", 1);
add_assoc_string(z_reason_texts, "4089", "Network priority parameter not allowed for this channel type.", 1);
add_assoc_string(z_reason_texts, "6117", "Length is negative.", 1);


