ADD_MQ_REASON_TXT(0, "No reason to report.");
ADD_MQ_REASON_TXT(900, "Lowest value for an application-defined reason code returned by a data-conversion exit.");
ADD_MQ_REASON_TXT(999, "Highest value for application-defined reason code returned by a data-conversion exit.");
ADD_MQ_REASON_TXT(2001, "Alias base queue not a valid type.");
ADD_MQ_REASON_TXT(2002, "Application already connected.");
ADD_MQ_REASON_TXT(2003, "Unit of work encountered fatal error or backed out.");
ADD_MQ_REASON_TXT(2004, "Buffer parameter not valid.");
ADD_MQ_REASON_TXT(2005, "Buffer length parameter not valid.");
ADD_MQ_REASON_TXT(2006, "Length of character attributes not valid.");
ADD_MQ_REASON_TXT(2007, "Character attributes string not valid.");
ADD_MQ_REASON_TXT(2008, "Not enough space allowed for character attributes.");
ADD_MQ_REASON_TXT(2009, "Connection to queue manager lost.");
ADD_MQ_REASON_TXT(2010, "Data length parameter not valid.");
ADD_MQ_REASON_TXT(2011, "Name of dynamic queue not valid.");
ADD_MQ_REASON_TXT(2012, "Call not valid in environment.");
ADD_MQ_REASON_TXT(2013, "Expiry time not valid.");
ADD_MQ_REASON_TXT(2014, "Feedback code not valid.");
ADD_MQ_REASON_TXT(2016, "Gets inhibited for the queue.");
ADD_MQ_REASON_TXT(2017, "No more handles available.");
ADD_MQ_REASON_TXT(2018, "Connection handle not valid.");
ADD_MQ_REASON_TXT(2019, "Object handle not valid.");
ADD_MQ_REASON_TXT(2020, "Value for inhibit-get or inhibit-put queue attribute not valid.");
ADD_MQ_REASON_TXT(2021, "Count of integer attributes not valid.");
ADD_MQ_REASON_TXT(2022, "Not enough space allowed for integer attributes.");
ADD_MQ_REASON_TXT(2023, "Integer attributes array not valid.");
ADD_MQ_REASON_TXT(2024, "No more messages can be handled within current unit of work.");
ADD_MQ_REASON_TXT(2025, "Maximum number of connections reached.");
ADD_MQ_REASON_TXT(2026, "Message descriptor not valid.");
ADD_MQ_REASON_TXT(2027, "Missing reply-to queue.");
ADD_MQ_REASON_TXT(2029, "Message type in message descriptor not valid.");
ADD_MQ_REASON_TXT(2030, "Message length greater than maximum for queue.");
ADD_MQ_REASON_TXT(2031, "Message length greater than maximum for queue manager.");
ADD_MQ_REASON_TXT(2033, "No message available.");
ADD_MQ_REASON_TXT(2034, "Browse cursor not positioned on message.");
ADD_MQ_REASON_TXT(2035, "Not authorized for access.");
ADD_MQ_REASON_TXT(2036, "Queue not open for browse.");
ADD_MQ_REASON_TXT(2037, "Queue not open for input.");
ADD_MQ_REASON_TXT(2038, "Queue not open for inquire.");
ADD_MQ_REASON_TXT(2039, "Queue not open for output.");
ADD_MQ_REASON_TXT(2040, "Queue not open for set.");
ADD_MQ_REASON_TXT(2041, "Object definition changed since opened.");
ADD_MQ_REASON_TXT(2042, "Object already open with conflicting options.");
ADD_MQ_REASON_TXT(2043, "Object type not valid.");
ADD_MQ_REASON_TXT(2044, "Object descriptor structure not valid.");
ADD_MQ_REASON_TXT(2045, "Option not valid for object type.");
ADD_MQ_REASON_TXT(2046, "Options not valid or not consistent.");
ADD_MQ_REASON_TXT(2047, "Persistence not valid.");
ADD_MQ_REASON_TXT(2048, "Message on a temporary dynamic queue cannot be persistent.");
ADD_MQ_REASON_TXT(2049, "Message Priority exceeds maximum value supported.");
ADD_MQ_REASON_TXT(2050, "Message priority not valid.");
ADD_MQ_REASON_TXT(2051, "Put calls inhibited for the queue.");
ADD_MQ_REASON_TXT(2052, "Queue has been deleted.");
ADD_MQ_REASON_TXT(2053, "Queue already contains maximum number of messages.");
ADD_MQ_REASON_TXT(2055, "Queue contains one or more messages or uncommitted put or get requests.");
ADD_MQ_REASON_TXT(2056, "No space available on disk for queue.");
ADD_MQ_REASON_TXT(2057, "Queue type not valid.");
ADD_MQ_REASON_TXT(2058, "Queue manager name not valid or not known.");
ADD_MQ_REASON_TXT(2059, "Queue manager not available for connection.");
ADD_MQ_REASON_TXT(2061, "Report options in message descriptor not valid.");
ADD_MQ_REASON_TXT(2062, "A message is already marked.");
ADD_MQ_REASON_TXT(2063, "Security error occurred.");
ADD_MQ_REASON_TXT(2065, "Count of selectors not valid.");
ADD_MQ_REASON_TXT(2066, "Count of selectors too big.");
ADD_MQ_REASON_TXT(2067, "Attribute selector not valid.");
ADD_MQ_REASON_TXT(2068, "Selector not applicable to queue type.");
ADD_MQ_REASON_TXT(2069, "Signal outstanding for this handle.");
ADD_MQ_REASON_TXT(2070, "No message returned (but signal request accepted).");
ADD_MQ_REASON_TXT(2071, "Insufficient storage available.");
ADD_MQ_REASON_TXT(2072, "Syncpoint support not available.");
ADD_MQ_REASON_TXT(2075, "Value for trigger-control attribute not valid.");
ADD_MQ_REASON_TXT(2076, "Value for trigger-depth attribute not valid.");
ADD_MQ_REASON_TXT(2077, "Value for trigger-message-priority attribute not valid.");
ADD_MQ_REASON_TXT(2078, "Value for trigger-type attribute not valid.");
ADD_MQ_REASON_TXT(2079, "Truncated message returned (processing completed).");
ADD_MQ_REASON_TXT(2080, "Truncated message returned (processing not completed).");
ADD_MQ_REASON_TXT(2082, "Unknown alias base queue.");
ADD_MQ_REASON_TXT(2085, "Unknown object name.");
ADD_MQ_REASON_TXT(2086, "Unknown object queue manager.");
ADD_MQ_REASON_TXT(2087, "Unknown remote queue manager.");
ADD_MQ_REASON_TXT(2090, "Wait interval in MQGMO not valid.");
ADD_MQ_REASON_TXT(2091, "Transmission queue not local.");
ADD_MQ_REASON_TXT(2092, "Transmission queue with wrong usage.");
ADD_MQ_REASON_TXT(2093, "Queue not open for pass all context.");
ADD_MQ_REASON_TXT(2094, "Queue not open for pass identity context.");
ADD_MQ_REASON_TXT(2095, "Queue not open for set all context.");
ADD_MQ_REASON_TXT(2096, "Queue not open for set identity context.");
ADD_MQ_REASON_TXT(2097, "Queue handle referred to does not save context.");
ADD_MQ_REASON_TXT(2098, "Context not available for queue handle referred to.");
ADD_MQ_REASON_TXT(2099, "Signal field not valid.");
ADD_MQ_REASON_TXT(2100, "Object already exists.");
ADD_MQ_REASON_TXT(2101, "Object damaged.");
ADD_MQ_REASON_TXT(2102, "Insufficient system resources available.");
ADD_MQ_REASON_TXT(2103, "Another queue manager already connected.");
ADD_MQ_REASON_TXT(2104, "Report option(s) in message descriptor not recognized.");
ADD_MQ_REASON_TXT(2105, "Storage class error.");
ADD_MQ_REASON_TXT(2106, "COD report option not valid for XCF queue.");
ADD_MQ_REASON_TXT(2107, "MQXWAIT call canceled.");
ADD_MQ_REASON_TXT(2108, "Invocation of MQXWAIT call not valid.");
ADD_MQ_REASON_TXT(2109, "Call suppressed by exit program.");
ADD_MQ_REASON_TXT(2110, "Message format not valid.");
ADD_MQ_REASON_TXT(2111, "Source coded character set identifier not valid.");
ADD_MQ_REASON_TXT(2112, "Source integer encoding not recognized.");
ADD_MQ_REASON_TXT(2113, "Packed-decimal encoding in message not recognized.");
ADD_MQ_REASON_TXT(2114, "Floating-point encoding in message not recognized.");
ADD_MQ_REASON_TXT(2115, "Target coded character set identifier not valid.");
ADD_MQ_REASON_TXT(2116, "Target integer encoding not recognized.");
ADD_MQ_REASON_TXT(2117, "Packed-decimal encoding specified by receiver not recognized.");
ADD_MQ_REASON_TXT(2118, "Floating-point encoding specified by receiver not recognized.");
ADD_MQ_REASON_TXT(2119, "Application message data not converted.");
ADD_MQ_REASON_TXT(2120, "Converted data too big for buffer.");
ADD_MQ_REASON_TXT(2121, "No participating resource managers registered.");
ADD_MQ_REASON_TXT(2122, "Participating resource manager not available.");
ADD_MQ_REASON_TXT(2123, "Result of commit or back-out operation is mixed.");
ADD_MQ_REASON_TXT(2124, "Result of commit operation is pending.");
ADD_MQ_REASON_TXT(2125, "Bridge started.");
ADD_MQ_REASON_TXT(2126, "Bridge stopped.");
ADD_MQ_REASON_TXT(2127, "Insufficient storage for adapter.");
ADD_MQ_REASON_TXT(2128, "Unit of work already started.");
ADD_MQ_REASON_TXT(2129, "Unable to load adapter connection module.");
ADD_MQ_REASON_TXT(2130, "Unable to load adapter service module.");
ADD_MQ_REASON_TXT(2131, "Adapter subsystem definition module not valid.");
ADD_MQ_REASON_TXT(2132, "Unable to load adapter subsystem definition module.");
ADD_MQ_REASON_TXT(2133, "Unable to load data conversion services modules.");
ADD_MQ_REASON_TXT(2134, "Begin-options structure not valid.");
ADD_MQ_REASON_TXT(2135, "Distribution header structure not valid.");
ADD_MQ_REASON_TXT(2136, "Multiple reason codes returned.");
ADD_MQ_REASON_TXT(2137, "Object not opened successfully.");
ADD_MQ_REASON_TXT(2138, "Unable to load adapter disconnection module.");
ADD_MQ_REASON_TXT(2139, "Connect-options structure not valid.");
ADD_MQ_REASON_TXT(2140, "Wait request rejected by CICS.");
ADD_MQ_REASON_TXT(2141, "Dead letter header structure not valid.");
ADD_MQ_REASON_TXT(2142, "MQ header structure not valid.");
ADD_MQ_REASON_TXT(2143, "Source length parameter not valid.");
ADD_MQ_REASON_TXT(2144, "Target length parameter not valid.");
ADD_MQ_REASON_TXT(2145, "Source buffer parameter not valid.");
ADD_MQ_REASON_TXT(2146, "Target buffer parameter not valid.");
ADD_MQ_REASON_TXT(2148, "IMS information header structure not valid.");
ADD_MQ_REASON_TXT(2149, "PCF structures not valid.");
ADD_MQ_REASON_TXT(2150, "DBCS string not valid.");
ADD_MQ_REASON_TXT(2152, "Object name not valid.");
ADD_MQ_REASON_TXT(2153, "Object queue-manager name not valid.");
ADD_MQ_REASON_TXT(2154, "Number of records present not valid.");
ADD_MQ_REASON_TXT(2155, "Object records not valid.");
ADD_MQ_REASON_TXT(2156, "Response records not valid.");
ADD_MQ_REASON_TXT(2157, "Primary and home ASIDs differ.");
ADD_MQ_REASON_TXT(2158, "Put message record flags not valid.");
ADD_MQ_REASON_TXT(2159, "Put message records not valid.");
ADD_MQ_REASON_TXT(2160, "Connection identifier already in use.");
ADD_MQ_REASON_TXT(2161, "Queue manager quiescing.");
ADD_MQ_REASON_TXT(2162, "Queue manager shutting down.");
ADD_MQ_REASON_TXT(2163, "Recovery coordinator already exists.");
ADD_MQ_REASON_TXT(2173, "Put-message options structure not valid.");
ADD_MQ_REASON_TXT(2183, "Unable to load API crossing exit.");
ADD_MQ_REASON_TXT(2184, "Remote queue name not valid.");
ADD_MQ_REASON_TXT(2185, "Inconsistent persistence specification.");
ADD_MQ_REASON_TXT(2186, "Get-message options structure not valid.");
ADD_MQ_REASON_TXT(2187, "Requested function not supported by CICS bridge.");
ADD_MQ_REASON_TXT(2188, "Call rejected by cluster-workload exit.");
ADD_MQ_REASON_TXT(2189, "Cluster name resolution failed.");
ADD_MQ_REASON_TXT(2190, "Converted string too big for field.");
ADD_MQ_REASON_TXT(2191, "Character trigger message structure not valid.");
ADD_MQ_REASON_TXT(2192, "Page set data set full.");
ADD_MQ_REASON_TXT(2193, "Error accessing page set data set.");
ADD_MQ_REASON_TXT(2194, "Object name not valid for object type.");
ADD_MQ_REASON_TXT(2195, "Unexpected error occurred.");
ADD_MQ_REASON_TXT(2196, "Unknown transmission queue.");
ADD_MQ_REASON_TXT(2197, "Unknown default transmission queue.");
ADD_MQ_REASON_TXT(2198, "Default transmission queue not local.");
ADD_MQ_REASON_TXT(2199, "Default transmission queue usage error.");
ADD_MQ_REASON_TXT(2201, "Name in use.");
ADD_MQ_REASON_TXT(2202, "Connection quiescing.");
ADD_MQ_REASON_TXT(2203, "Connection shutting down.");
ADD_MQ_REASON_TXT(2204, "Adapter not available.");
ADD_MQ_REASON_TXT(2206, "Message-identifier error.");
ADD_MQ_REASON_TXT(2207, "Correlation-identifier error.");
ADD_MQ_REASON_TXT(2208, "File-system error.");
ADD_MQ_REASON_TXT(2209, "No message locked.");
ADD_MQ_REASON_TXT(2217, "Not authorized for connection.");
ADD_MQ_REASON_TXT(2218, "Message length greater than maximum for channel.");
ADD_MQ_REASON_TXT(2219, "MQI call reentered before previous call complete.");
ADD_MQ_REASON_TXT(2220, "Reference message header structure not valid.");
ADD_MQ_REASON_TXT(2222, "Queue manager created.");
ADD_MQ_REASON_TXT(2223, "Queue manager unavailable.");
ADD_MQ_REASON_TXT(2224, "Queue depth high limit reached or exceeded.");
ADD_MQ_REASON_TXT(2225, "Queue depth low limit reached or exceeded.");
ADD_MQ_REASON_TXT(2226, "Queue service interval high.");
ADD_MQ_REASON_TXT(2227, "Queue service interval ok.");
ADD_MQ_REASON_TXT(2232, "Unit of work not started.");
ADD_MQ_REASON_TXT(2233, "Automatic channel definition succeeded.");
ADD_MQ_REASON_TXT(2234, "Automatic channel definition failed.");
ADD_MQ_REASON_TXT(2235, "PCF header structure not valid.");
ADD_MQ_REASON_TXT(2236, "PCF integer list parameter structure not valid.");
ADD_MQ_REASON_TXT(2237, "PCF integer parameter structure not valid.");
ADD_MQ_REASON_TXT(2238, "PCF string list parameter structure not valid.");
ADD_MQ_REASON_TXT(2239, "PCF string parameter structure not valid.");
ADD_MQ_REASON_TXT(2241, "Message group not complete.");
ADD_MQ_REASON_TXT(2242, "Logical message not complete.");
ADD_MQ_REASON_TXT(2243, "Message segments have differing CCSIDs.");
ADD_MQ_REASON_TXT(2244, "Message segments have differing encodings.");
ADD_MQ_REASON_TXT(2245, "Inconsistent unit-of-work specification.");
ADD_MQ_REASON_TXT(2246, "Message under cursor not valid for retrieval.");
ADD_MQ_REASON_TXT(2247, "Match options not valid.");
ADD_MQ_REASON_TXT(2248, "Message descriptor extension not valid.");
ADD_MQ_REASON_TXT(2249, "Message flags not valid.");
ADD_MQ_REASON_TXT(2250, "Message sequence number not valid.");
ADD_MQ_REASON_TXT(2251, "Message segment offset not valid.");
ADD_MQ_REASON_TXT(2252, "Original length not valid.");
ADD_MQ_REASON_TXT(2253, "Length of data in message segment is zero.");
ADD_MQ_REASON_TXT(2255, "Unit of work not available for the queue manager to use.");
ADD_MQ_REASON_TXT(2256, "Wrong version of MQGMO supplied.");
ADD_MQ_REASON_TXT(2257, "Wrong version of MQMD supplied.");
ADD_MQ_REASON_TXT(2258, "Group identifier not valid.");
ADD_MQ_REASON_TXT(2259, "Inconsistent browse specification.");
ADD_MQ_REASON_TXT(2260, "Transmission queue header structure not valid.");
ADD_MQ_REASON_TXT(2261, "Source environment data error.");
ADD_MQ_REASON_TXT(2262, "Source name data error.");
ADD_MQ_REASON_TXT(2263, "Destination environment data error.");
ADD_MQ_REASON_TXT(2264, "Destination name data error.");
ADD_MQ_REASON_TXT(2265, "Trigger message structure not valid.");
ADD_MQ_REASON_TXT(2266, "Cluster workload exit failed.");
ADD_MQ_REASON_TXT(2267, "Unable to load cluster workload exit.");
ADD_MQ_REASON_TXT(2268, "Put calls inhibited for all queues in cluster.");
ADD_MQ_REASON_TXT(2270, "No destination queues available.");
ADD_MQ_REASON_TXT(2273, "Error processing MQCONN call.");
ADD_MQ_REASON_TXT(2274, "Option not valid in environment.");
ADD_MQ_REASON_TXT(2277, "Channel definition not valid.");
ADD_MQ_REASON_TXT(2278, "Client connection fields not valid.");
ADD_MQ_REASON_TXT(2279, "Channel stopped by user.");
ADD_MQ_REASON_TXT(2280, "Configuration handle not valid.");
ADD_MQ_REASON_TXT(2281, "Function identifier not valid for service.");
ADD_MQ_REASON_TXT(2282, "Channel started.");
ADD_MQ_REASON_TXT(2283, "Channel stopped.");
ADD_MQ_REASON_TXT(2284, "Channel conversion error.");
ADD_MQ_REASON_TXT(2285, "Underlying service not available.");
ADD_MQ_REASON_TXT(2286, "Initialization failed for an undefined reason.");
ADD_MQ_REASON_TXT(2287, "Termination failed for an undefined reason.");
ADD_MQ_REASON_TXT(2288, "Queue name not found.");
ADD_MQ_REASON_TXT(2289, "Unexpected error occurred accessing service.");
ADD_MQ_REASON_TXT(2290, "Queue object already exists.");
ADD_MQ_REASON_TXT(2291, "Unable to determine the user ID.");
ADD_MQ_REASON_TXT(2292, "Entity unknown to service.");
ADD_MQ_REASON_TXT(2293, "Authorization entity unknown to service.");
ADD_MQ_REASON_TXT(2294, "Reference object unknown.");
ADD_MQ_REASON_TXT(2295, "Channel activated.");
ADD_MQ_REASON_TXT(2296, "Channel cannot be activated.");
ADD_MQ_REASON_TXT(2297, "Unit of work canceled.");
ADD_MQ_REASON_TXT(2299, "Selector has wrong data type.");
ADD_MQ_REASON_TXT(2300, "Command type not valid.");
ADD_MQ_REASON_TXT(2301, "Multiple instances of system data item not valid.");
ADD_MQ_REASON_TXT(2302, "System data item is read-only and cannot be altered.");
ADD_MQ_REASON_TXT(2303, "Data could not be converted into a bag.");
ADD_MQ_REASON_TXT(2304, "Selector not within valid range for call.");
ADD_MQ_REASON_TXT(2305, "Selector occurs more than once in bag.");
ADD_MQ_REASON_TXT(2306, "Index not present.");
ADD_MQ_REASON_TXT(2307, "String parameter not valid.");
ADD_MQ_REASON_TXT(2308, "Encoding not supported.");
ADD_MQ_REASON_TXT(2309, "Selector not present in bag.");
ADD_MQ_REASON_TXT(2310, "OutSelector parameter not valid.");
ADD_MQ_REASON_TXT(2311, "String truncated (too long for output buffer).");
ADD_MQ_REASON_TXT(2312, "Selector implies a data type not valid for call.");
ADD_MQ_REASON_TXT(2313, "Data type of item differs from previous occurrence of selector.");
ADD_MQ_REASON_TXT(2314, "Index not valid.");
ADD_MQ_REASON_TXT(2315, "System bag is read-only and cannot be altered.");
ADD_MQ_REASON_TXT(2316, "ItemCount parameter not valid.");
ADD_MQ_REASON_TXT(2317, "Format not supported.");
ADD_MQ_REASON_TXT(2318, "System selector not supported.");
ADD_MQ_REASON_TXT(2319, "ItemValue parameter not valid.");
ADD_MQ_REASON_TXT(2320, "Bag handle not valid.");
ADD_MQ_REASON_TXT(2321, "Parameter missing.");
ADD_MQ_REASON_TXT(2322, "Command server not available.");
ADD_MQ_REASON_TXT(2323, "StringLength parameter not valid.");
ADD_MQ_REASON_TXT(2324, "Command code is not a recognized inquiry command.");
ADD_MQ_REASON_TXT(2325, "Input bag contains one or more nested bags.");
ADD_MQ_REASON_TXT(2326, "Bag has wrong type for intended use.");
ADD_MQ_REASON_TXT(2327, "ItemType parameter not valid.");
ADD_MQ_REASON_TXT(2328, "System bag is read-only and cannot be deleted.");
ADD_MQ_REASON_TXT(2329, "System data item is read-only and cannot be deleted.");
ADD_MQ_REASON_TXT(2330, "Coded character set identifier parameter not valid.");
ADD_MQ_REASON_TXT(2331, "Use of message token not valid.");
ADD_MQ_REASON_TXT(2332, "Message data does not begin with MQWIH.");
ADD_MQ_REASON_TXT(2333, "MQWIH structure not valid.");
ADD_MQ_REASON_TXT(2334, "MQRFH structure not valid.");
ADD_MQ_REASON_TXT(2335, "NameValueString field not valid.");
ADD_MQ_REASON_TXT(2336, "Command not valid.");
ADD_MQ_REASON_TXT(2337, "Parameter not valid.");
ADD_MQ_REASON_TXT(2338, "Duplicate parameter.");
ADD_MQ_REASON_TXT(2339, "Parameter missing.");
ADD_MQ_REASON_TXT(2367, "Create Object");
ADD_MQ_REASON_TXT(2368, "Change Object");
ADD_MQ_REASON_TXT(2369, "Delete Object");
ADD_MQ_REASON_TXT(2370, "Refresh Object");
ADD_MQ_REASON_TXT(3001, "Type not valid.");
ADD_MQ_REASON_TXT(3002, "Structure length not valid.");
ADD_MQ_REASON_TXT(3003, "Structure version number is not valid.");
ADD_MQ_REASON_TXT(3004, "Message sequence number not valid.");
ADD_MQ_REASON_TXT(3005, "Control option not valid.");
ADD_MQ_REASON_TXT(3006, "Parameter count not valid.");
ADD_MQ_REASON_TXT(3007, "Command identifier not valid.");
ADD_MQ_REASON_TXT(3008, "Command failed.");
ADD_MQ_REASON_TXT(3009, "Structure length not valid.");
ADD_MQ_REASON_TXT(3010, "Structure length not valid.");
ADD_MQ_REASON_TXT(3011, "String length not valid.");
ADD_MQ_REASON_TXT(3012, "Force value not valid.");
ADD_MQ_REASON_TXT(3013, "Structure type not valid.");
ADD_MQ_REASON_TXT(3014, "Parameter identifier is not valid.");
ADD_MQ_REASON_TXT(3015, "Parameter identifier is not valid.");
ADD_MQ_REASON_TXT(3016, "Message length not valid.");
ADD_MQ_REASON_TXT(3017, "Duplicate parameter.");
ADD_MQ_REASON_TXT(3018, "Duplicate parameter.");
ADD_MQ_REASON_TXT(3019, "Parameter count too small.");
ADD_MQ_REASON_TXT(3020, "Parameter count too big.");
ADD_MQ_REASON_TXT(3021, "Queue already exists in cell.");
ADD_MQ_REASON_TXT(3022, "Queue type not valid.");
ADD_MQ_REASON_TXT(3023, "Format not valid.");
ADD_MQ_REASON_TXT(3025, "Replace value not valid.");
ADD_MQ_REASON_TXT(3026, "Duplicate parameter.");
ADD_MQ_REASON_TXT(3027, "Count of parameter values not valid.");
ADD_MQ_REASON_TXT(3028, "Structure length not valid.");
ADD_MQ_REASON_TXT(3029, "Mode value not valid.");
ADD_MQ_REASON_TXT(3029, "Quiesce value not valid.");
ADD_MQ_REASON_TXT(3030, "Message sequence number not valid.");
ADD_MQ_REASON_TXT(3031, "Data count not valid.");
ADD_MQ_REASON_TXT(3032, "Ping Channel command failed.");
ADD_MQ_REASON_TXT(3034, "Channel type not valid.");
ADD_MQ_REASON_TXT(3035, "Parameter sequence not valid.");
ADD_MQ_REASON_TXT(3036, "Transmission protocol type not valid.");
ADD_MQ_REASON_TXT(3037, "Batch size not valid.");
ADD_MQ_REASON_TXT(3038, "Disconnection interval not valid.");
ADD_MQ_REASON_TXT(3039, "Short retry count not valid.");
ADD_MQ_REASON_TXT(3040, "Short timer value not valid.");
ADD_MQ_REASON_TXT(3041, "Long retry count not valid.");
ADD_MQ_REASON_TXT(3042, "Long timer not valid.");
ADD_MQ_REASON_TXT(3043, "Sequence wrap number not valid.");
ADD_MQ_REASON_TXT(3044, "Maximum message length not valid.");
ADD_MQ_REASON_TXT(3045, "Put authority value not valid.");
ADD_MQ_REASON_TXT(3046, "Purge value not valid.");
ADD_MQ_REASON_TXT(3047, "Parameter identifier is not valid.");
ADD_MQ_REASON_TXT(3048, "Message truncated.");
ADD_MQ_REASON_TXT(3049, "Coded character-set identifier error.");
ADD_MQ_REASON_TXT(3050, "Encoding error.");
ADD_MQ_REASON_TXT(3052, "Data conversion value not valid.");
ADD_MQ_REASON_TXT(3053, "In-doubt value not valid.");
ADD_MQ_REASON_TXT(3054, "Escape type not valid.");
ADD_MQ_REASON_TXT(3062, "Channel table value not valid.");
ADD_MQ_REASON_TXT(3063, "Message channel agent type not valid.");
ADD_MQ_REASON_TXT(3064, "Channel instance type not valid.");
ADD_MQ_REASON_TXT(3065, "Channel status not found.");
ADD_MQ_REASON_TXT(3066, "Duplicate parameter.");
ADD_MQ_REASON_TXT(3067, "Total string length error.");
ADD_MQ_REASON_TXT(3068, "Name count value not valid.");
ADD_MQ_REASON_TXT(3069, "String length not valid.");
ADD_MQ_REASON_TXT(3086, "Queue manager coded character set identifier error.");
ADD_MQ_REASON_TXT(3088, "ClusterName and ClusterNamelist attributes conflict.");
ADD_MQ_REASON_TXT(3089, "RepositoryName and RepositoryNamelist attributes conflict.");
ADD_MQ_REASON_TXT(3090, "Cluster queue cannot be a transmission queue.");
ADD_MQ_REASON_TXT(3091, "Action value not valid.");
ADD_MQ_REASON_TXT(3092, "Library for requested communications protocol could not be loaded.");
ADD_MQ_REASON_TXT(3093, "NetBIOS listener name not defined.");
ADD_MQ_REASON_TXT(3095, "Conflicting parameters.");
ADD_MQ_REASON_TXT(3150, "Content based filter expression not valid.");
ADD_MQ_REASON_TXT(3151, "Wrong user.");
ADD_MQ_REASON_TXT(4001, "Object already exists.");
ADD_MQ_REASON_TXT(4002, "Object has wrong type.");
ADD_MQ_REASON_TXT(4003, "New and existing objects have different type.");
ADD_MQ_REASON_TXT(4004, "Object is open.");
ADD_MQ_REASON_TXT(4005, "Attribute value not valid.");
ADD_MQ_REASON_TXT(4006, "Queue manager not known.");
ADD_MQ_REASON_TXT(4007, "Action not valid for the queue of specified type.");
ADD_MQ_REASON_TXT(4008, "Object name not valid.");
ADD_MQ_REASON_TXT(4009, "Allocation failed.");
ADD_MQ_REASON_TXT(4010, "Remote system not available.");
ADD_MQ_REASON_TXT(4011, "Configuration error.");
ADD_MQ_REASON_TXT(4012, "Connection refused.");
ADD_MQ_REASON_TXT(4013, "Invalid connection name.");
ADD_MQ_REASON_TXT(4014, "Send failed.");
ADD_MQ_REASON_TXT(4015, "Received data error.");
ADD_MQ_REASON_TXT(4016, "Receive failed.");
ADD_MQ_REASON_TXT(4017, "Connection closed.");
ADD_MQ_REASON_TXT(4018, "Not enough storage available.");
ADD_MQ_REASON_TXT(4019, "Communications manager not available.");
ADD_MQ_REASON_TXT(4020, "Listener not started.");
ADD_MQ_REASON_TXT(4024, "Bind failed.");
ADD_MQ_REASON_TXT(4025, "Channel in-doubt.");
ADD_MQ_REASON_TXT(4026, "MQCONN call failed.");
ADD_MQ_REASON_TXT(4027, "MQOPEN call failed.");
ADD_MQ_REASON_TXT(4028, "MQGET call failed.");
ADD_MQ_REASON_TXT(4029, "MQPUT call failed.");
ADD_MQ_REASON_TXT(4030, "Ping error.");
ADD_MQ_REASON_TXT(4031, "Channel in use.");
ADD_MQ_REASON_TXT(4032, "Channel not found.");
ADD_MQ_REASON_TXT(4033, "Remote channel not known.");
ADD_MQ_REASON_TXT(4034, "Remote queue manager not available.");
ADD_MQ_REASON_TXT(4035, "Remote queue manager terminating.");
ADD_MQ_REASON_TXT(4036, "MQINQ call failed.");
ADD_MQ_REASON_TXT(4037, "Queue is not a transmission queue.");
ADD_MQ_REASON_TXT(4038, "Channel disabled.");
ADD_MQ_REASON_TXT(4039, "User exit not available.");
ADD_MQ_REASON_TXT(4040, "Commit failed.");
ADD_MQ_REASON_TXT(4041, "Parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4042, "Channel already exists.");
ADD_MQ_REASON_TXT(4043, "Data too large.");
ADD_MQ_REASON_TXT(4044, "Channel name error.");
ADD_MQ_REASON_TXT(4045, "Transmission queue name error.");
ADD_MQ_REASON_TXT(4047, "Message channel agent name error.");
ADD_MQ_REASON_TXT(4048, "Channel send exit name error.");
ADD_MQ_REASON_TXT(4049, "Channel security exit name error.");
ADD_MQ_REASON_TXT(4050, "Channel message exit name error.");
ADD_MQ_REASON_TXT(4051, "Channel receive exit name error.");
ADD_MQ_REASON_TXT(4052, "Transmission queue name not allowed for this channel type.");
ADD_MQ_REASON_TXT(4053, "Message channel agent name not allowed for this channel type.");
ADD_MQ_REASON_TXT(4054, "Disconnection interval not allowed for this channel type.");
ADD_MQ_REASON_TXT(4055, "Short retry parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4056, "Short timer parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4057, "Long retry parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4058, "Long timer parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4059, "Put authority parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4060, "Keepalive interval not valid.");
ADD_MQ_REASON_TXT(4061, "Connection name parameter required but missing.");
ADD_MQ_REASON_TXT(4062, "Error in connection name parameter.");
ADD_MQ_REASON_TXT(4063, "MQSET call failed.");
ADD_MQ_REASON_TXT(4064, "Channel not active.");
ADD_MQ_REASON_TXT(4065, "Channel terminated by security exit.");
ADD_MQ_REASON_TXT(4067, "Dynamic queue scope error.");
ADD_MQ_REASON_TXT(4068, "Cell directory is not available.");
ADD_MQ_REASON_TXT(4069, "Message retry count not valid.");
ADD_MQ_REASON_TXT(4070, "Message-retry count parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4071, "Channel message-retry exit name error.");
ADD_MQ_REASON_TXT(4072, "Message-retry exit parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4073, "Message retry interval not valid.");
ADD_MQ_REASON_TXT(4074, "Message-retry interval parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4075, "Nonpersistent message speed not valid.");
ADD_MQ_REASON_TXT(4076, "Nonpersistent message speed parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4077, "Heartbeat interval not valid.");
ADD_MQ_REASON_TXT(4078, "Heartbeat interval parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4079, "Channel automatic definition error.");
ADD_MQ_REASON_TXT(4080, "Channel automatic definition parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4081, "Channel automatic definition event error.");
ADD_MQ_REASON_TXT(4082, "Channel automatic definition event parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4083, "Channel automatic definition exit name error.");
ADD_MQ_REASON_TXT(4084, "Channel automatic definition exit parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4085, "Action suppressed by exit program.");
ADD_MQ_REASON_TXT(4086, "Batch interval not valid.");
ADD_MQ_REASON_TXT(4087, "Batch interval parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(4088, "Network priority value is not valid.");
ADD_MQ_REASON_TXT(4089, "Network priority parameter not allowed for this channel type.");
ADD_MQ_REASON_TXT(6117, "Length is negative.");


