/* Completion Codes */
REGISTER_LONG_CONSTANT("MQSERIES_MQCC_OK", MQCC_OK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCC_WARNING", MQCC_WARNING, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCC_FAILED", MQCC_FAILED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCC_UNKNOWN", MQCC_UNKNOWN, CONST_PERSISTENT);

/* Reason Codes */
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NONE", MQRC_NONE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_APPL_FIRST", MQRC_APPL_FIRST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_APPL_LAST", MQRC_APPL_LAST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ALIAS_BASE_Q_TYPE_ERROR", MQRC_ALIAS_BASE_Q_TYPE_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ALREADY_CONNECTED", MQRC_ALREADY_CONNECTED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BACKED_OUT", 2003, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BUFFER_ERROR", 2004, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BUFFER_LENGTH_ERROR", 2005, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHAR_ATTR_LENGTH_ERROR", 2006, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHAR_ATTRS_ERROR", 2007, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHAR_ATTRS_TOO_SHORT", 2008, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONNECTION_BROKEN", 2009, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DATA_LENGTH_ERROR", 2010, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DYNAMIC_Q_NAME_ERROR", 2011, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ENVIRONMENT_ERROR", 2012, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_EXPIRY_ERROR", 2013, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FEEDBACK_ERROR", 2014, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_GET_INHIBITED", 2016, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HANDLE_NOT_AVAILABLE", 2017, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HCONN_ERROR", 2018, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HOBJ_ERROR", 2019, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INHIBIT_VALUE_ERROR", 2020, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INT_ATTR_COUNT_ERROR", 2021, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INT_ATTR_COUNT_TOO_SMALL", 2022, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INT_ATTRS_ARRAY_ERROR", 2023, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYNCPOINT_LIMIT_REACHED", 2024, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MAX_CONNS_LIMIT_REACHED", 2025, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MD_ERROR", 2026, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MISSING_REPLY_TO_Q", 2027, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_TYPE_ERROR", 2029, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_TOO_BIG_FOR_Q", 2030, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_TOO_BIG_FOR_Q_MGR", 2031, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_MSG_AVAILABLE", 2033, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_MSG_UNDER_CURSOR", 2034, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_AUTHORIZED", 2035, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_BROWSE", 2036, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_INPUT", 2037, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_INQUIRE", 2038, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_OUTPUT", 2039, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_SET", 2040, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_CHANGED", 2041, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_IN_USE", 2042, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_TYPE_ERROR", 2043, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OD_ERROR", 2044, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OPTION_NOT_VALID_FOR_TYPE", 2045, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OPTIONS_ERROR", 2046, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PERSISTENCE_ERROR", 2047, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PERSISTENT_NOT_ALLOWED", 2048, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PRIORITY_EXCEEDS_MAXIMUM", 2049, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PRIORITY_ERROR", 2050, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PUT_INHIBITED", 2051, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_DELETED", 2052, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_FULL", 2053, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_NOT_EMPTY", 2055, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_SPACE_NOT_AVAILABLE", 2056, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_TYPE_ERROR", 2057, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_NAME_ERROR", 2058, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_NOT_AVAILABLE", 2059, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REPORT_OPTIONS_ERROR", 2061, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SECOND_MARK_NOT_ALLOWED", 2062, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SECURITY_ERROR", 2063, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_COUNT_ERROR", 2065, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_LIMIT_EXCEEDED", 2066, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_ERROR", 2067, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_NOT_FOR_TYPE", 2068, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SIGNAL_OUTSTANDING", 2069, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SIGNAL_REQUEST_ACCEPTED", 2070, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STORAGE_NOT_AVAILABLE", 2071, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYNCPOINT_NOT_AVAILABLE", 2072, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRIGGER_CONTROL_ERROR", 2075, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRIGGER_DEPTH_ERROR", 2076, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRIGGER_MSG_PRIORITY_ERR", 2077, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRIGGER_TYPE_ERROR", 2078, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRUNCATED_MSG_ACCEPTED", 2079, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRUNCATED_MSG_FAILED", 2080, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_ALIAS_BASE_Q", 2082, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_OBJECT_NAME", 2085, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_OBJECT_Q_MGR", 2086, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_REMOTE_Q_MGR", 2087, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WAIT_INTERVAL_ERROR", 2090, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_XMIT_Q_TYPE_ERROR", 2091, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_XMIT_Q_USAGE_ERROR", 2092, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_PASS_ALL", 2093, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_PASS_IDENT", 2094, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_SET_ALL", 2095, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN_FOR_SET_IDENT", 2096, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONTEXT_HANDLE_ERROR", 2097, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONTEXT_NOT_AVAILABLE", 2098, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SIGNAL1_ERROR", 2099, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_ALREADY_EXISTS", 2100, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_DAMAGED", 2101, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RESOURCE_PROBLEM", 2102, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ANOTHER_Q_MGR_CONNECTED", 2103, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_REPORT_OPTION", 2104, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STORAGE_CLASS_ERROR", 2105, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_COD_NOT_VALID_FOR_XCF_Q", 2106, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_XWAIT_CANCELED", 2107, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_XWAIT_ERROR", 2108, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SUPPRESSED_BY_EXIT", 2109, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FORMAT_ERROR", 2110, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_CCSID_ERROR", 2111, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_INTEGER_ENC_ERROR", 2112, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_DECIMAL_ENC_ERROR", 2113, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_FLOAT_ENC_ERROR", 2114, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_CCSID_ERROR", 2115, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_INTEGER_ENC_ERROR", 2116, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_DECIMAL_ENC_ERROR", 2117, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_FLOAT_ENC_ERROR", 2118, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_CONVERTED", 2119, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONVERTED_MSG_TOO_BIG", 2120, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TRUNCATED", 2120, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_EXTERNAL_PARTICIPANTS", 2121, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PARTICIPANT_NOT_AVAILABLE", 2122, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OUTCOME_MIXED", 2123, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OUTCOME_PENDING", 2124, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BRIDGE_STARTED", 2125, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BRIDGE_STOPPED", 2126, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_STORAGE_SHORTAGE", 2127, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UOW_IN_PROGRESS", 2128, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_CONN_LOAD_ERROR", 2129, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_SERV_LOAD_ERROR", 2130, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_DEFS_ERROR", 2131, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_DEFS_LOAD_ERROR", 2132, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_CONV_LOAD_ERROR", 2133, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BO_ERROR", 2134, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DH_ERROR", 2135, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MULTIPLE_REASONS", 2136, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OPEN_FAILED", 2137, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_DISC_LOAD_ERROR", 2138, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CNO_ERROR", 2139, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CICS_WAIT_FAILED", 2140, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DLH_ERROR", 2141, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HEADER_ERROR", 2142, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_LENGTH_ERROR", 2143, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_LENGTH_ERROR", 2144, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SOURCE_BUFFER_ERROR", 2145, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TARGET_BUFFER_ERROR", 2146, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_IIH_ERROR", 2148, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PCF_ERROR", 2149, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DBCS_ERROR", 2150, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_NAME_ERROR", 2152, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_Q_MGR_NAME_ERROR", 2153, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RECS_PRESENT_ERROR", 2154, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_RECORDS_ERROR", 2155, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RESPONSE_RECORDS_ERROR", 2156, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ASID_MISMATCH", 2157, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PMO_RECORD_FLAGS_ERROR", 2158, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PUT_MSG_RECORDS_ERROR", 2159, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONN_ID_IN_USE", 2160, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_QUIESCING", 2161, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_STOPPING", 2162, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DUPLICATE_RECOV_COORD", 2163, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PMO_ERROR", 2173, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_API_EXIT_NOT_FOUND", 2182, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_API_EXIT_LOAD_ERROR", 2183, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REMOTE_Q_NAME_ERROR", 2184, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_PERSISTENCE", 2185, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_GMO_ERROR", 2186, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CICS_BRIDGE_RESTRICTION", 2187, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STOPPED_BY_CLUSTER_EXIT", 2188, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLUSTER_RESOLUTION_ERROR", 2189, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONVERTED_STRING_TOO_BIG", 2190, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TMC_ERROR", 2191, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PAGESET_FULL", 2192, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STORAGE_MEDIUM_FULL", 2192, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PAGESET_ERROR", 2193, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NAME_NOT_VALID_FOR_TYPE", 2194, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNEXPECTED_ERROR", 2195, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_XMIT_Q", 2196, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_DEF_XMIT_Q", 2197, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DEF_XMIT_Q_TYPE_ERROR", 2198, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DEF_XMIT_Q_USAGE_ERROR", 2199, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NAME_IN_USE", 2201, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONNECTION_QUIESCING", 2202, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONNECTION_STOPPING", 2203, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ADAPTER_NOT_AVAILABLE", 2204, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_ID_ERROR", 2206, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CORREL_ID_ERROR", 2207, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FILE_SYSTEM_ERROR", 2208, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_MSG_LOCKED", 2209, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FILE_NOT_AUDITED", 2216, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONNECTION_NOT_AUTHORIZED", 2217, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_TOO_BIG_FOR_CHANNEL", 2218, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CALL_IN_PROGRESS", 2219, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RMH_ERROR", 2220, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_ACTIVE", 2222, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_MGR_NOT_ACTIVE", 2223, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_DEPTH_HIGH", 2224, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_DEPTH_LOW", 2225, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_SERVICE_INTERVAL_HIGH", 2226, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_SERVICE_INTERVAL_OK", 2227, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNIT_OF_WORK_NOT_STARTED", 2232, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_AUTO_DEF_OK", 2233, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_AUTO_DEF_ERROR", 2234, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CFH_ERROR", 2235, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CFIL_ERROR", 2236, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CFIN_ERROR", 2237, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CFSL_ERROR", 2238, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CFST_ERROR", 2239, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCOMPLETE_GROUP", 2241, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCOMPLETE_MSG", 2242, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_CCSIDS", 2243, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_ENCODINGS", 2244, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_UOW", 2245, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INVALID_MSG_UNDER_CURSOR", 2246, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MATCH_OPTIONS_ERROR", 2247, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MDE_ERROR", 2248, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_FLAGS_ERROR", 2249, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_SEQ_NUMBER_ERROR", 2250, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OFFSET_ERROR", 2251, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ORIGINAL_LENGTH_ERROR", 2252, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SEGMENT_LENGTH_ZERO", 2253, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UOW_NOT_AVAILABLE", 2255, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WRONG_GMO_VERSION", 2256, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WRONG_MD_VERSION", 2257, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_GROUP_ID_ERROR", 2258, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_BROWSE", 2259, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_XQH_ERROR", 2260, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SRC_ENV_ERROR", 2261, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SRC_NAME_ERROR", 2262, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DEST_ENV_ERROR", 2263, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DEST_NAME_ERROR", 2264, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TM_ERROR", 2265, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLUSTER_EXIT_ERROR", 2266, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLUSTER_EXIT_LOAD_ERROR", 2267, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLUSTER_PUT_INHIBITED", 2268, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLUSTER_RESOURCE_ERROR", 2269, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_DESTINATIONS_AVAILABLE", 2270, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONN_TAG_IN_USE", 2271, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PARTIALLY_CONVERTED", 2272, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONNECTION_ERROR", 2273, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OPTION_ENVIRONMENT_ERROR", 2274, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CD_ERROR", 2277, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CLIENT_CONN_ERROR", 2278, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_STOPPED_BY_USER", 2279, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HCONFIG_ERROR", 2280, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FUNCTION_ERROR", 2281, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_STARTED", 2282, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_STOPPED", 2283, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_CONV_ERROR", 2284, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SERVICE_NOT_AVAILABLE", 2285, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INITIALIZATION_FAILED", 2286, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_TERMINATION_FAILED", 2287, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_Q_NAME", 2288, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SERVICE_ERROR", 2289, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_ALREADY_EXISTS", 2290, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_USER_ID_NOT_AVAILABLE", 2291, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_ENTITY", 2292, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_AUTH_ENTITY", 2293, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNKNOWN_REF_OBJECT", 2294, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_ACTIVATED", 2295, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_NOT_ACTIVATED", 2296, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UOW_CANCELED", 2297, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FUNCTION_NOT_SUPPORTED", 2298, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_TYPE_ERROR", 2299, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_COMMAND_TYPE_ERROR", 2300, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MULTIPLE_INSTANCE_ERROR", 2301, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYSTEM_ITEM_NOT_ALTERABLE", 2302, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BAG_CONVERSION_ERROR", 2303, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_OUT_OF_RANGE", 2304, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_NOT_UNIQUE", 2305, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INDEX_NOT_PRESENT", 2306, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STRING_ERROR", 2307, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ENCODING_NOT_SUPPORTED", 2308, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_NOT_PRESENT", 2309, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OUT_SELECTOR_ERROR", 2310, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STRING_TRUNCATED", 2311, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_WRONG_TYPE", 2312, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_ITEM_TYPE", 2313, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INDEX_ERROR", 2314, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYSTEM_BAG_NOT_ALTERABLE", 2315, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ITEM_COUNT_ERROR", 2316, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_FORMAT_NOT_SUPPORTED", 2317, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SELECTOR_NOT_SUPPORTED", 2318, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ITEM_VALUE_ERROR", 2319, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HBAG_ERROR", 2320, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_PARAMETER_MISSING", 2321, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CMD_SERVER_NOT_AVAILABLE", 2322, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STRING_LENGTH_ERROR", 2323, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INQUIRY_COMMAND_ERROR", 2324, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NESTED_BAG_NOT_SUPPORTED", 2325, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BAG_WRONG_TYPE", 2326, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ITEM_TYPE_ERROR", 2327, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYSTEM_BAG_NOT_DELETABLE", 2328, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SYSTEM_ITEM_NOT_DELETABLE", 2329, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CODED_CHAR_SET_ID_ERROR", 2330, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_TOKEN_ERROR", 2331, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MISSING_WIH", 2332, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WIH_ERROR", 2333, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_ERROR", 2334, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_STRING_ERROR", 2335, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_COMMAND_ERROR", 2336, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_PARM_ERROR", 2337, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_DUPLICATE_PARM", 2338, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RFH_PARM_MISSING", 2339, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHAR_CONVERSION_ERROR", 2340, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UCS2_CONVERSION_ERROR", 2341, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DB2_NOT_AVAILABLE", 2342, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_NOT_UNIQUE", 2343, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONN_TAG_NOT_RELEASED", 2344, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_NOT_AVAILABLE", 2345, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_STRUC_IN_USE", 2346, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_STRUC_LIST_HDR_IN_USE", 2347, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_STRUC_AUTH_FAILED", 2348, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_STRUC_ERROR", 2349, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONN_TAG_NOT_USABLE", 2350, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_GLOBAL_UOW_CONFLICT", 2351, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_LOCAL_UOW_CONFLICT", 2352, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_HANDLE_IN_USE_FOR_UOW", 2353, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UOW_ENLISTMENT_ERROR", 2354, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UOW_MIX_NOT_SUPPORTED", 2355, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WXP_ERROR", 2356, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CURRENT_RECORD_ERROR", 2357, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NEXT_OFFSET_ERROR", 2358, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_RECORD_AVAILABLE", 2359, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_OBJECT_LEVEL_INCOMPATIBLE", 2360, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NEXT_RECORD_ERROR", 2361, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BACKOUT_THRESHOLD_REACHED", 2362, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_MSG_NOT_MATCHED", 2363, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_JMS_FORMAT_ERROR", 2364, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SEGMENTS_NOT_SUPPORTED", 2365, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WRONG_CF_LEVEL", 2366, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONFIG_CREATE_OBJECT", 2367, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONFIG_CHANGE_OBJECT", 2368, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONFIG_DELETE_OBJECT", 2369, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONFIG_REFRESH_OBJECT", 2370, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CHANNEL_SSL_ERROR", 2371, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CF_STRUC_FAILED", 2373, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_API_EXIT_ERROR", 2374, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_API_EXIT_INIT_ERROR", 2375, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_API_EXIT_TERM_ERROR", 2376, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_EXIT_REASON_ERROR", 2377, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_RESERVED_VALUE_ERROR", 2378, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_DATA_AVAILABLE", 2379, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SCO_ERROR", 2380, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_KEY_REPOSITORY_ERROR", 2381, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CRYPTO_HARDWARE_ERROR", 2382, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_AUTH_INFO_REC_COUNT_ERROR", 2383, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_AUTH_INFO_REC_ERROR", 2384, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_AIR_ERROR", 2385, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_AUTH_INFO_TYPE_ERROR", 2386, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_AUTH_INFO_CONN_NAME_ERROR", 2387, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_LDAP_USER_NAME_ERROR", 2388, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_LDAP_USER_NAME_LENGTH_ERR", 2389, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_LDAP_PASSWORD_ERROR", 2390, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_ALREADY_INITIALIZED", 2391, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_CONFIG_ERROR", 2392, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_INITIALIZATION_ERROR", 2393, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_Q_INDEX_TYPE_ERROR", 2394, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_NOT_ALLOWED", 2396, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_JSSE_ERROR", 2397, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_PEER_NAME_MISMATCH", 2398, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_PEER_NAME_ERROR", 2399, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_UNSUPPORTED_CIPHER_SUITE", 2400, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_CERTIFICATE_REVOKED", 2401, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_SSL_CERT_STORE_ERROR", 2402, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REOPEN_EXCL_INPUT_ERROR", 6100, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REOPEN_INQUIRE_ERROR", 6101, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REOPEN_SAVED_CONTEXT_ERR", 6102, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REOPEN_TEMPORARY_Q_ERROR", 6103, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ATTRIBUTE_LOCKED", 6104, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CURSOR_NOT_VALID", 6105, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ENCODING_ERROR", 6106, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STRUC_ID_ERROR", 6107, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NULL_POINTER", 6108, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_CONNECTION_REFERENCE", 6109, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NO_BUFFER", 6110, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BINARY_DATA_LENGTH_ERROR", 6111, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_BUFFER_NOT_AUTOMATIC", 6112, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INSUFFICIENT_BUFFER", 6113, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INSUFFICIENT_DATA", 6114, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DATA_TRUNCATED", 6115, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_ZERO_LENGTH", 6116, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NEGATIVE_LENGTH", 6117, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NEGATIVE_OFFSET", 6118, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_FORMAT", 6119, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_OBJECT_STATE", 6120, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONTEXT_OBJECT_NOT_VALID", 6121, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_CONTEXT_OPEN_ERROR", 6122, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_STRUC_LENGTH_ERROR", 6123, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_CONNECTED", 6124, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_NOT_OPEN", 6125, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_DISTRIBUTION_LIST_EMPTY", 6126, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_INCONSISTENT_OPEN_OPTIONS", 6127, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_WRONG_VERSION", 6128, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRC_REFERENCE_ERROR", 6129, CONST_PERSISTENT);

/* Open Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_INPUT_AS_Q_DEF", 0x00000001, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_INPUT_SHARED", 0x00000002, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_INPUT_EXCLUSIVE", 0x00000004, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_BROWSE", 0x00000008, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_OUTPUT", 0x00000010, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_INQUIRE", 0x00000020, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_SET", 0x00000040, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_BIND_ON_OPEN", 0x00004000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_BIND_NOT_FIXED", 0x00008000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_BIND_AS_Q_DEF", 0x00000000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_SAVE_ALL_CONTEXT", 0x00000080, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_PASS_IDENTITY_CONTEXT", 0x00000100, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_PASS_ALL_CONTEXT", 0x00000200, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_SET_IDENTITY_CONTEXT", 0x00000400, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_SET_ALL_CONTEXT", 0x00000800, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_ALTERNATE_USER_AUTHORITY", 0x00001000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_FAIL_IF_QUIESCING", 0x00002000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOO_RESOLVE_NAMES", 0x00010000, CONST_PERSISTENT);  /* C++ option only */
REGISTER_STRING_CONSTANT("MQSERIES_MQGMO_STRUC_ID", MQGMO_STRUC_ID, CONST_PERSISTENT);  /* C++ option only */

/* close options */
REGISTER_LONG_CONSTANT("MQSERIES_MQCO_NONE", MQCO_NONE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCO_DELETE", MQCO_DELETE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCO_DELETE_PURGE",MQCO_DELETE_PURGE, CONST_PERSISTENT);


 /*********************************************************************/
 /*  Values Related to MQGMO Structure                                */
 /*********************************************************************/

/* Structure Version Number */
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_VERSION_1", 1, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_VERSION_2", 2, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_VERSION_3", 3, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_CURRENT_VERSION", 3, CONST_PERSISTENT);

/* Get-Message Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_WAIT", 0x00000001, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_NO_WAIT", 0x00000000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_SET_SIGNAL", 0x00000008, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_FAIL_IF_QUIESCING", 0x00002000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_SYNCPOINT", 0x00000002, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_SYNCPOINT_IF_PERSISTENT", 0x00001000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_NO_SYNCPOINT", 0x00000004, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_MARK_SKIP_BACKOUT", 0x00000080, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_BROWSE_FIRST", 0x00000010, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_BROWSE_NEXT", 0x00000020, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_BROWSE_MSG_UNDER_CURSOR", 0x00000800, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_MSG_UNDER_CURSOR", 0x00000100, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_LOCK", 0x00000200, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_UNLOCK", 0x00000400, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_ACCEPT_TRUNCATED_MSG", 0x00000040, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_CONVERT", 0x00004000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_LOGICAL_ORDER", 0x00008000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_COMPLETE_MSG", 0x00010000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_ALL_MSGS_AVAILABLE", 0x00020000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_ALL_SEGMENTS_AVAILABLE", 0x00040000, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQGMO_NONE", 0x00000000, CONST_PERSISTENT);

/* Wait Interval */
REGISTER_LONG_CONSTANT("MQSERIES_MQWI_UNLIMITED", MQWI_UNLIMITED, CONST_PERSISTENT);

 /* Signal Values */
REGISTER_LONG_CONSTANT("MQSERIES_MQEC_MSG_ARRIVED", MQEC_MSG_ARRIVED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQEC_WAIT_INTERVAL_EXPIRED", MQEC_WAIT_INTERVAL_EXPIRED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQEC_WAIT_CANCELED", MQEC_WAIT_CANCELED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQEC_Q_MGR_QUIESCING", MQEC_Q_MGR_QUIESCING, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQEC_CONNECTION_QUIESCING",MQEC_CONNECTION_QUIESCING , CONST_PERSISTENT);

 /* Match Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_MSG_ID",MQMO_MATCH_MSG_ID , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_CORREL_ID", MQMO_MATCH_CORREL_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_GROUP_ID", MQMO_MATCH_GROUP_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_MSG_SEQ_NUMBER",MQMO_MATCH_MSG_SEQ_NUMBER , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_OFFSET",MQMO_MATCH_OFFSET , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_MATCH_MSG_TOKEN",MQMO_MATCH_MSG_TOKEN , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMO_NONE", MQMO_NONE, CONST_PERSISTENT);

 /* Group Status */
// char const
//REGISTER_STRING_CONSTANT("MQSERIES_MQGS_NOT_IN_GROUP", MQGS_NOT_IN_GROUP, CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQGS_MSG_IN_GROUP",MQGS_MSG_IN_GROUP , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQGS_LAST_MSG_IN_GROUP", MQGS_LAST_MSG_IN_GROUP, CONST_PERSISTENT);

 /* Segment Status */
//REGISTER_STRING_CONSTANT("MQSERIES_MQSS_NOT_A_SEGMENT",MQSS_NOT_A_SEGMENT , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQSS_SEGMENT",MQSS_SEGMENT , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQSS_LAST_SEGMENT",MQSS_LAST_SEGMENT , CONST_PERSISTENT);

 /* Segmentation */
//REGISTER_STRING_CONSTANT("MQSERIES_MQSEG_INHIBITED",MQSEG_INHIBITED , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQSEG_ALLOWED", MQSEG_ALLOWED, CONST_PERSISTENT);

 /* Message Token */
REGISTER_STRING_CONSTANT("MQSERIES_MQMTOK_NONE", MQMTOK_NONE, CONST_PERSISTENT);


 /* Returned Length */
REGISTER_LONG_CONSTANT("MQSERIES_MQRL_UNDEFINED", MQRL_UNDEFINED, CONST_PERSISTENT);


 /*********************************************************************/
 /*  Values Related to MQMD Structure                                 */
 /*********************************************************************/

 /* Structure Version Number */
REGISTER_LONG_CONSTANT("MQSERIES_MQMD_VERSION_1", MQMD_VERSION_1, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMD_VERSION_2", MQMD_VERSION_2, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMD_CURRENT_VERSION", MQMD_CURRENT_VERSION, CONST_PERSISTENT);

 /* Report Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXCEPTION", MQRO_EXCEPTION, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXCEPTION_WITH_DATA", MQRO_EXCEPTION_WITH_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXCEPTION_WITH_FULL_DATA", MQRO_EXCEPTION_WITH_FULL_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXPIRATION", MQRO_EXPIRATION, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXPIRATION_WITH_DATA", MQRO_EXPIRATION_WITH_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_EXPIRATION_WITH_FULL_DATA", MQRO_EXPIRATION_WITH_FULL_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COA", MQRO_COA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COA_WITH_DATA", MQRO_COA_WITH_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COA_WITH_FULL_DATA", MQRO_COA_WITH_FULL_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COD", MQRO_COD, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COD_WITH_DATA", MQRO_COD_WITH_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COD_WITH_FULL_DATA", MQRO_COD_WITH_FULL_DATA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_PAN", MQRO_PAN, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_NAN", MQRO_NAN, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_NEW_MSG_ID", MQRO_NEW_MSG_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_PASS_MSG_ID", MQRO_PASS_MSG_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_COPY_MSG_ID_TO_CORREL_ID", MQRO_COPY_MSG_ID_TO_CORREL_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_PASS_CORREL_ID", MQRO_PASS_CORREL_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_DEAD_LETTER_Q", MQRO_DEAD_LETTER_Q, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_DISCARD_MSG", MQRO_DISCARD_MSG, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_NONE", MQRO_NONE, CONST_PERSISTENT);

 /* Report Options Masks */
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_REJECT_UNSUP_MASK", MQRO_REJECT_UNSUP_MASK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_ACCEPT_UNSUP_MASK", MQRO_ACCEPT_UNSUP_MASK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQRO_ACCEPT_UNSUP_IF_XMIT_MASK", MQRO_ACCEPT_UNSUP_IF_XMIT_MASK, CONST_PERSISTENT);

/* Message Types */
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_SYSTEM_FIRST", MQMT_SYSTEM_FIRST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_REQUEST", MQMT_REQUEST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_REPLY", MQMT_REPLY, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_DATAGRAM", MQMT_DATAGRAM, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_REPORT", MQMT_REPORT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_MQE_FIELDS_FROM_MQE", MQMT_MQE_FIELDS_FROM_MQE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_MQE_FIELDS", MQMT_MQE_FIELDS, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_SYSTEM_LAST", MQMT_SYSTEM_LAST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_APPL_FIRST", MQMT_APPL_FIRST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMT_APPL_LAST", MQMT_APPL_LAST, CONST_PERSISTENT);

/* Expiry */
REGISTER_LONG_CONSTANT("MQSERIES_MQEI_UNLIMITED", MQEI_UNLIMITED, CONST_PERSISTENT);

 /* Feedback Values */
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_NONE",MQFB_NONE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_SYSTEM_FIRST",MQFB_SYSTEM_FIRST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_QUIT",MQFB_QUIT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_EXPIRATION",MQFB_EXPIRATION , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_COA", MQFB_COA, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_COD",MQFB_COD , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CHANNEL_COMPLETED",MQFB_CHANNEL_COMPLETED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CHANNEL_FAIL_RETRY", MQFB_CHANNEL_FAIL_RETRY, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CHANNEL_FAIL",MQFB_CHANNEL_FAIL , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_APPL_CANNOT_BE_STARTED", MQFB_APPL_CANNOT_BE_STARTED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_TM_ERROR",MQFB_TM_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_APPL_TYPE_ERROR",MQFB_APPL_TYPE_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_STOPPED_BY_MSG_EXIT", MQFB_STOPPED_BY_MSG_EXIT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_XMIT_Q_MSG_ERROR",MQFB_XMIT_Q_MSG_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_PAN", MQFB_PAN, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_NAN",MQFB_NAN , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_STOPPED_BY_CHAD_EXIT", MQFB_STOPPED_BY_CHAD_EXIT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_STOPPED_BY_PUBSUB_EXIT",MQFB_STOPPED_BY_PUBSUB_EXIT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_NOT_A_REPOSITORY_MSG", MQFB_NOT_A_REPOSITORY_MSG, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_BIND_OPEN_CLUSRCVR_DEL", MQFB_BIND_OPEN_CLUSRCVR_DEL, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_DATA_LENGTH_ZERO",MQFB_DATA_LENGTH_ZERO , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_DATA_LENGTH_NEGATIVE",MQFB_DATA_LENGTH_NEGATIVE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_DATA_LENGTH_TOO_BIG", MQFB_DATA_LENGTH_TOO_BIG, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_BUFFER_OVERFLOW", MQFB_BUFFER_OVERFLOW, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_LENGTH_OFF_BY_ONE",MQFB_LENGTH_OFF_BY_ONE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_IIH_ERROR", MQFB_IIH_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_NOT_AUTHORIZED_FOR_IMS",MQFB_NOT_AUTHORIZED_FOR_IMS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_IMS_ERROR", MQFB_IMS_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_IMS_FIRST",MQFB_IMS_FIRST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_IMS_LAST",MQFB_IMS_LAST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_INTERNAL_ERROR", MQFB_CICS_INTERNAL_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_NOT_AUTHORIZED",MQFB_CICS_NOT_AUTHORIZED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_BRIDGE_FAILURE",MQFB_CICS_BRIDGE_FAILURE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_CORREL_ID_ERROR", MQFB_CICS_CORREL_ID_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_CCSID_ERROR",MQFB_CICS_CCSID_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_ENCODING_ERROR", MQFB_CICS_ENCODING_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_CIH_ERROR", MQFB_CICS_CIH_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_UOW_ERROR",MQFB_CICS_UOW_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_COMMAREA_ERROR",MQFB_CICS_COMMAREA_ERROR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_APPL_NOT_STARTED",MQFB_CICS_APPL_NOT_STARTED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_APPL_ABENDED", MQFB_CICS_APPL_ABENDED, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_DLQ_ERROR",MQFB_CICS_DLQ_ERROR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_CICS_UOW_BACKED_OUT",MQFB_CICS_UOW_BACKED_OUT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_SYSTEM_LAST",MQFB_SYSTEM_LAST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_APPL_FIRST",MQFB_APPL_FIRST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQFB_APPL_LAST", MQFB_APPL_LAST, CONST_PERSISTENT);

 /* Encoding */
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_NATIVE", MQENC_NATIVE, CONST_PERSISTENT);

 /* Encoding Masks */
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_INTEGER_MASK", MQENC_INTEGER_MASK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_DECIMAL_MASK",MQENC_DECIMAL_MASK , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_FLOAT_MASK", MQENC_FLOAT_MASK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_RESERVED_MASK",MQENC_RESERVED_MASK , CONST_PERSISTENT);

 /* Encodings for Binary Integers */
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_INTEGER_UNDEFINED",MQENC_INTEGER_UNDEFINED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_INTEGER_NORMAL",MQENC_INTEGER_NORMAL , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_INTEGER_REVERSED", MQENC_INTEGER_REVERSED, CONST_PERSISTENT);

 /* Encodings for Packed-Decimal Integers */
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_DECIMAL_UNDEFINED",MQENC_DECIMAL_UNDEFINED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_DECIMAL_NORMAL",MQENC_DECIMAL_NORMAL , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_DECIMAL_REVERSED",MQENC_DECIMAL_REVERSED , CONST_PERSISTENT);

 /* Encodings for Floating-Point Numbers */
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_FLOAT_UNDEFINED",MQENC_FLOAT_UNDEFINED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_FLOAT_IEEE_NORMAL",MQENC_FLOAT_IEEE_NORMAL , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_FLOAT_IEEE_REVERSED",MQENC_FLOAT_IEEE_REVERSED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQENC_FLOAT_S390",MQENC_FLOAT_S390 , CONST_PERSISTENT);

 /* Coded Character-Set Identifiers */
REGISTER_LONG_CONSTANT("MQSERIES_MQCCSI_UNDEFINED",MQCCSI_UNDEFINED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCCSI_DEFAULT",MQCCSI_DEFAULT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCCSI_Q_MGR",MQCCSI_Q_MGR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCCSI_INHERIT", MQCCSI_INHERIT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCCSI_EMBEDDED", MQCCSI_EMBEDDED, CONST_PERSISTENT);

 /* Formats */
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_NONE", MQFMT_NONE, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_ADMIN", MQFMT_ADMIN, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_CHANNEL_COMPLETED", MQFMT_CHANNEL_COMPLETED, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_CICS", MQFMT_CICS, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_COMMAND_1", MQFMT_COMMAND_1, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_COMMAND_2", MQFMT_COMMAND_2, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_DEAD_LETTER_HEADER", MQFMT_DEAD_LETTER_HEADER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_DIST_HEADER", MQFMT_DIST_HEADER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_EVENT", MQFMT_EVENT, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_IMS", MQFMT_IMS, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_IMS_VAR_STRING", MQFMT_IMS_VAR_STRING, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_MD_EXTENSION", MQFMT_MD_EXTENSION, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_PCF", MQFMT_PCF, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_REF_MSG_HEADER", MQFMT_REF_MSG_HEADER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_RF_HEADER", MQFMT_RF_HEADER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_RF_HEADER_2", MQFMT_RF_HEADER_2, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_STRING", MQFMT_STRING, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_TRIGGER", MQFMT_TRIGGER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_WORK_INFO_HEADER", MQFMT_WORK_INFO_HEADER, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQFMT_XMIT_Q_HEADER", MQFMT_XMIT_Q_HEADER, CONST_PERSISTENT);


 /* Priority */
REGISTER_LONG_CONSTANT("MQSERIES_MQPRI_PRIORITY_AS_Q_DEF", MQPRI_PRIORITY_AS_Q_DEF, CONST_PERSISTENT);

 /* Persistence Values */
REGISTER_LONG_CONSTANT("MQSERIES_MQPER_NOT_PERSISTENT", MQPER_NOT_PERSISTENT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPER_PERSISTENT", MQPER_PERSISTENT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPER_PERSISTENCE_AS_Q_DEF", MQPER_PERSISTENCE_AS_Q_DEF, CONST_PERSISTENT);


 /* Message Identifier */
REGISTER_STRING_CONSTANT("MQSERIES_MQMI_NONE",MQMI_NONE , CONST_PERSISTENT);


 /* Correlation Identifier */
REGISTER_STRING_CONSTANT("MQSERIES_MQCI_NONE", MQCI_NONE, CONST_PERSISTENT);
REGISTER_STRING_CONSTANT("MQSERIES_MQCI_NEW_SESSION", MQCI_NEW_SESSION, CONST_PERSISTENT);


 /* Accounting Token */
REGISTER_STRING_CONSTANT("MQSERIES_MQACT_NONE", MQACT_NONE , CONST_PERSISTENT);


 /* Accounting Token Type */
// not supported 
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_UNKNOWN",MQACTT_UNKNOWN , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_CICS_LUOW_ID",MQACTT_CICS_LUOW_ID , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_OS2_DEFAULT", MQACTT_OS2_DEFAULT, CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_DOS_DEFAULT",MQACTT_DOS_DEFAULT , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_UNIX_NUMERIC_ID",MQACTT_UNIX_NUMERIC_ID , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_OS400_ACCOUNT_TOKEN",MQACTT_OS400_ACCOUNT_TOKEN , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_WINDOWS_DEFAULT",MQACTT_WINDOWS_DEFAULT , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_NT_SECURITY_ID",MQACTT_NT_SECURITY_ID , CONST_PERSISTENT);
//REGISTER_STRING_CONSTANT("MQSERIES_MQACTT_USER", MQACTT_USER, CONST_PERSISTENT);

 /* Put Application Type */
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_UNKNOWN", MQAT_UNKNOWN, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_NO_CONTEXT",MQAT_NO_CONTEXT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_CICS",MQAT_CICS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_MVS", MQAT_MVS, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_OS390", MQAT_OS390, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_ZOS",MQAT_ZOS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_IMS",MQAT_IMS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_OS2",MQAT_OS2 , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_DOS",MQAT_DOS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_AIX", MQAT_AIX, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_UNIX",MQAT_UNIX , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_QMGR", MQAT_QMGR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_OS400",MQAT_OS400 , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_WINDOWS",MQAT_WINDOWS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_CICS_VSE",MQAT_CICS_VSE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_WINDOWS_NT",MQAT_WINDOWS_NT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_VMS", MQAT_VMS, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_GUARDIAN",MQAT_GUARDIAN , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_NSK",MQAT_NSK , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_VOS",MQAT_VOS , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_IMS_BRIDGE", MQAT_IMS_BRIDGE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_XCF",MQAT_XCF , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_CICS_BRIDGE",MQAT_CICS_BRIDGE , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_NOTES_AGENT",MQAT_NOTES_AGENT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_USER",MQAT_USER , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_BROKER", MQAT_BROKER, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_JAVA",MQAT_JAVA , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_DQM",MQAT_DQM , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_CHANNEL_INITIATOR",MQAT_CHANNEL_INITIATOR , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_DEFAULT", MQAT_DEFAULT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_USER_FIRST",MQAT_USER_FIRST , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQAT_USER_LAST",MQAT_USER_LAST , CONST_PERSISTENT);

 /* Group Identifier */
REGISTER_STRING_CONSTANT("MQSERIES_MQGI_NONE",MQGI_NONE , CONST_PERSISTENT);

 /* Message Flags */
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_SEGMENTATION_INHIBITED",MQMF_SEGMENTATION_INHIBITED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_SEGMENTATION_ALLOWED",MQMF_SEGMENTATION_ALLOWED , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_MSG_IN_GROUP",MQMF_MSG_IN_GROUP , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_LAST_MSG_IN_GROUP",MQMF_LAST_MSG_IN_GROUP , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_SEGMENT", MQMF_SEGMENT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_LAST_SEGMENT",MQMF_LAST_SEGMENT , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_NONE",MQMF_NONE , CONST_PERSISTENT);

 /* Message Flags Masks */
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_REJECT_UNSUP_MASK", MQMF_REJECT_UNSUP_MASK, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_ACCEPT_UNSUP_MASK",MQMF_ACCEPT_UNSUP_MASK , CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQMF_ACCEPT_UNSUP_IF_XMIT_MASK",MQMF_ACCEPT_UNSUP_IF_XMIT_MASK , CONST_PERSISTENT);

 /* Original Length */
REGISTER_LONG_CONSTANT("MQSERIES_MQOL_UNDEFINED", MQOL_UNDEFINED, CONST_PERSISTENT);


/* Begin Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQBO_VERSION_1", MQBO_VERSION_1, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQBO_CURRENT_VERSION", MQBO_CURRENT_VERSION, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQBO_NONE", MQBO_NONE, CONST_PERSISTENT);


 /* PMO Structure Identifier */
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_VERSION_1", MQPMO_VERSION_1, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_VERSION_2", MQPMO_VERSION_2, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_CURRENT_VERSION", MQPMO_CURRENT_VERSION, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_CURRENT_LENGTH", MQPMO_CURRENT_LENGTH, CONST_PERSISTENT);

 /* Put-Message Options */
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_SYNCPOINT", MQPMO_SYNCPOINT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_NO_SYNCPOINT", MQPMO_NO_SYNCPOINT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_NEW_MSG_ID", MQPMO_NEW_MSG_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_NEW_CORREL_ID", MQPMO_NEW_CORREL_ID, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_LOGICAL_ORDER", MQPMO_LOGICAL_ORDER, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_NO_CONTEXT", MQPMO_NO_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_DEFAULT_CONTEXT", MQPMO_DEFAULT_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_PASS_IDENTITY_CONTEXT", MQPMO_PASS_IDENTITY_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_PASS_ALL_CONTEXT", MQPMO_PASS_ALL_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_SET_IDENTITY_CONTEXT", MQPMO_SET_IDENTITY_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_SET_ALL_CONTEXT", MQPMO_SET_ALL_CONTEXT, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_ALTERNATE_USER_AUTHORITY", MQPMO_ALTERNATE_USER_AUTHORITY, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_FAIL_IF_QUIESCING", MQPMO_FAIL_IF_QUIESCING, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQPMO_NONE", MQPMO_NONE, CONST_PERSISTENT);

/* MQCNO - Connect options */
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_VERSION_1", MQCNO_VERSION_1, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_VERSION_2", MQCNO_VERSION_2, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_CURRENT_VERSION", MQCNO_CURRENT_VERSION, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_STANDARD_BINDING", MQCNO_STANDARD_BINDING, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_FASTPATH_BINDING", MQCNO_FASTPATH_BINDING, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCNO_NONE", MQCNO_NONE, CONST_PERSISTENT);

/* Transport types for channel definitions */
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_LOCAL",MQXPT_LOCAL, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_LU62",MQXPT_LU62, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_TCP",MQXPT_TCP, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_NETBIOS",MQXPT_NETBIOS, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_SPX",MQXPT_SPX, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_DECNET",MQXPT_DECNET, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQXPT_UDP",MQXPT_UDP, CONST_PERSISTENT);

/* Object type for MQOpen */
REGISTER_LONG_CONSTANT("MQSERIES_MQOT_Q",MQOT_Q, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOT_NAMELIST",MQOT_NAMELIST, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOT_PROCESS",MQOT_PROCESS, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOT_Q_MGR",MQOT_Q_MGR, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQOT_RESERVED_1",MQOT_RESERVED_1, CONST_PERSISTENT);

/* Selectors for MQINQ */
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_ALTERATION_DATE", MQCA_ALTERATION_DATE, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_ALTERATION_TIME", MQCA_ALTERATION_TIME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_APPL_ID",MQCA_APPL_ID ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_AUTH_INFO_CONN_NAME",MQCA_AUTH_INFO_CONN_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_AUTH_INFO_DESC",MQCA_AUTH_INFO_DESC ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_AUTH_INFO_NAME", MQCA_AUTH_INFO_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_BACKOUT_REQ_Q_NAME",MQCA_BACKOUT_REQ_Q_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_BASE_Q_NAME",MQCA_BASE_Q_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CF_STRUC_DESC",MQCA_CF_STRUC_DESC ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CF_STRUC_NAME", MQCA_CF_STRUC_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CHANNEL_AUTO_DEF_EXIT", MQCA_CHANNEL_AUTO_DEF_EXIT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_DATE", MQCA_CLUSTER_DATE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_NAME",MQCA_CLUSTER_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_NAMELIST",MQCA_CLUSTER_NAMELIST ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_Q_MGR_NAME",MQCA_CLUSTER_Q_MGR_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_TIME", MQCA_CLUSTER_TIME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_WORKLOAD_DATA",MQCA_CLUSTER_WORKLOAD_DATA ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CLUSTER_WORKLOAD_EXIT",MQCA_CLUSTER_WORKLOAD_EXIT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_COMMAND_INPUT_Q_NAME", MQCA_COMMAND_INPUT_Q_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CREATION_DATE", MQCA_CREATION_DATE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_CREATION_TIME",MQCA_CREATION_TIME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_DEAD_LETTER_Q_NAME", MQCA_DEAD_LETTER_Q_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_DEF_XMIT_Q_NAME",MQCA_DEF_XMIT_Q_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_ENV_DATA", MQCA_ENV_DATA,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_FIRST", MQCA_FIRST,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_IGQ_USER_ID",MQCA_IGQ_USER_ID ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_INITIATION_Q_NAME", MQCA_INITIATION_Q_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_LAST", MQCA_LAST,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_LAST_USED",MQCA_LAST_USED ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_LDAP_PASSWORD",MQCA_LDAP_PASSWORD ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_LDAP_USER_NAME",MQCA_LDAP_USER_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_NAMELIST_DESC",MQCA_NAMELIST_DESC ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_NAMELIST_NAME",MQCA_NAMELIST_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_NAMES", MQCA_NAMES,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_PROCESS_DESC",MQCA_PROCESS_DESC ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_PROCESS_NAME",MQCA_PROCESS_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_Q_DESC", MQCA_Q_DESC,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_Q_MGR_DESC",MQCA_Q_MGR_DESC ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_Q_MGR_IDENTIFIER", MQCA_Q_MGR_IDENTIFIER,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_Q_MGR_NAME",MQCA_Q_MGR_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_Q_NAME",MQCA_Q_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_QSG_NAME", MQCA_QSG_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_REMOTE_Q_MGR_NAME",MQCA_REMOTE_Q_MGR_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_REMOTE_Q_NAME", MQCA_REMOTE_Q_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_REPOSITORY_NAME",MQCA_REPOSITORY_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_REPOSITORY_NAMELIST",MQCA_REPOSITORY_NAMELIST ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_SSL_CRL_NAMELIST", MQCA_SSL_CRL_NAMELIST,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_SSL_CRYPTO_HARDWARE",MQCA_SSL_CRYPTO_HARDWARE ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_SSL_KEY_REPOSITORY", MQCA_SSL_KEY_REPOSITORY,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_STORAGE_CLASS", MQCA_STORAGE_CLASS,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_STORAGE_CLASS_DESC", MQCA_STORAGE_CLASS_DESC,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_TRIGGER_DATA",MQCA_TRIGGER_DATA ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_USER_DATA", MQCA_USER_DATA,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_USER_LIST",MQCA_USER_LIST ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_XCF_GROUP_NAME",MQCA_XCF_GROUP_NAME ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_XCF_MEMBER_NAME", MQCA_XCF_MEMBER_NAME,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQCA_XMIT_Q_NAME", MQCA_XMIT_Q_NAME,CONST_PERSISTENT);

 /* Integer-Attribute Selectors */
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_APPL_TYPE", MQIA_APPL_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_ARCHIVE", MQIA_ARCHIVE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_AUTH_INFO_TYPE", MQIA_AUTH_INFO_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_AUTHORITY_EVENT",MQIA_AUTHORITY_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_BACKOUT_THRESHOLD",MQIA_BACKOUT_THRESHOLD ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CF_LEVEL", MQIA_CF_LEVEL,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CF_RECOVER", MQIA_CF_RECOVER,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CHANNEL_AUTO_DEF", MQIA_CHANNEL_AUTO_DEF,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CHANNEL_AUTO_DEF_EVENT", MQIA_CHANNEL_AUTO_DEF_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CLUSTER_Q_TYPE",MQIA_CLUSTER_Q_TYPE ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CLUSTER_WORKLOAD_LENGTH", MQIA_CLUSTER_WORKLOAD_LENGTH,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CODED_CHAR_SET_ID",MQIA_CODED_CHAR_SET_ID ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_COMMAND_LEVEL", MQIA_COMMAND_LEVEL,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CONFIGURATION_EVENT",MQIA_CONFIGURATION_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_CURRENT_Q_DEPTH",MQIA_CURRENT_Q_DEPTH ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DEF_BIND", MQIA_DEF_BIND,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DEF_INPUT_OPEN_OPTION", MQIA_DEF_INPUT_OPEN_OPTION,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DEF_PERSISTENCE",MQIA_DEF_PERSISTENCE ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DEF_PRIORITY", MQIA_DEF_PRIORITY,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DEFINITION_TYPE", MQIA_DEFINITION_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_DIST_LISTS",MQIA_DIST_LISTS ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_EXPIRY_INTERVAL",MQIA_EXPIRY_INTERVAL ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_FIRST", MQIA_FIRST,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_HARDEN_GET_BACKOUT",MQIA_HARDEN_GET_BACKOUT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_HIGH_Q_DEPTH", MQIA_HIGH_Q_DEPTH,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_IGQ_PUT_AUTHORITY",MQIA_IGQ_PUT_AUTHORITY ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_INDEX_TYPE", MQIA_INDEX_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_INHIBIT_EVENT", MQIA_INHIBIT_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_INHIBIT_GET", MQIA_INHIBIT_GET,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_INHIBIT_PUT", MQIA_INHIBIT_PUT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_INTRA_GROUP_QUEUING",MQIA_INTRA_GROUP_QUEUING ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_LAST", MQIA_LAST,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_LAST_USED",MQIA_LAST_USED ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_LOCAL_EVENT", MQIA_LOCAL_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MAX_HANDLES", MQIA_MAX_HANDLES,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MAX_MSG_LENGTH",MQIA_MAX_MSG_LENGTH ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MAX_PRIORITY",MQIA_MAX_PRIORITY ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MAX_Q_DEPTH",MQIA_MAX_Q_DEPTH ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MAX_UNCOMMITTED_MSGS",MQIA_MAX_UNCOMMITTED_MSGS ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MSG_DELIVERY_SEQUENCE", MQIA_MSG_DELIVERY_SEQUENCE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MSG_DEQ_COUNT",MQIA_MSG_DEQ_COUNT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_MSG_ENQ_COUNT", MQIA_MSG_ENQ_COUNT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_NAME_COUNT", MQIA_NAME_COUNT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_NAMELIST_TYPE", MQIA_NAMELIST_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_NPM_CLASS", MQIA_NPM_CLASS,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_OPEN_INPUT_COUNT", MQIA_OPEN_INPUT_COUNT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_OPEN_OUTPUT_COUNT", MQIA_OPEN_OUTPUT_COUNT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_PAGESET_ID", MQIA_PAGESET_ID,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_PERFORMANCE_EVENT",MQIA_PERFORMANCE_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_PLATFORM", MQIA_PLATFORM,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_DEPTH_HIGH_EVENT", MQIA_Q_DEPTH_HIGH_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_DEPTH_HIGH_LIMIT",MQIA_Q_DEPTH_HIGH_LIMIT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_DEPTH_LOW_EVENT", MQIA_Q_DEPTH_LOW_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_DEPTH_LOW_LIMIT", MQIA_Q_DEPTH_LOW_LIMIT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_DEPTH_MAX_EVENT",MQIA_Q_DEPTH_MAX_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_SERVICE_INTERVAL", MQIA_Q_SERVICE_INTERVAL,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_SERVICE_INTERVAL_EVENT", MQIA_Q_SERVICE_INTERVAL_EVENT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_Q_TYPE", MQIA_Q_TYPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_QSG_DISP",MQIA_QSG_DISP ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_REMOTE_EVENT",MQIA_REMOTE_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_RETENTION_INTERVAL",MQIA_RETENTION_INTERVAL ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_SCOPE", MQIA_SCOPE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_SHAREABILITY", MQIA_SHAREABILITY,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_SSL_TASKS",MQIA_SSL_TASKS ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_START_STOP_EVENT",MQIA_START_STOP_EVENT ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_SYNCPOINT", MQIA_SYNCPOINT,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TIME_SINCE_RESET",MQIA_TIME_SINCE_RESET ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TRIGGER_CONTROL",MQIA_TRIGGER_CONTROL ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TRIGGER_DEPTH",MQIA_TRIGGER_DEPTH ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TRIGGER_INTERVAL",MQIA_TRIGGER_INTERVAL ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TRIGGER_MSG_PRIORITY", MQIA_TRIGGER_MSG_PRIORITY,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_TRIGGER_TYPE",MQIA_TRIGGER_TYPE ,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_USAGE", MQIA_USAGE,CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQIA_USER_LIST",MQIA_USER_LIST ,CONST_PERSISTENT);


/* String Lengths */
REGISTER_LONG_CONSTANT("MQSERIES_MQ_ABEND_CODE_LENGTH", MQ_ABEND_CODE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_ACCOUNTING_TOKEN_LENGTH", MQ_ACCOUNTING_TOKEN_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_APPL_IDENTITY_DATA_LENGTH",MQ_APPL_IDENTITY_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_APPL_NAME_LENGTH", MQ_APPL_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_APPL_ORIGIN_DATA_LENGTH",MQ_APPL_ORIGIN_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_APPL_TAG_LENGTH",MQ_APPL_TAG_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_ARM_SUFFIX_LENGTH",MQ_ARM_SUFFIX_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_ATTENTION_ID_LENGTH",MQ_AUTH_INFO_CONN_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTH_INFO_CONN_NAME_LENGTH",MQ_AUTH_INFO_CONN_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTH_INFO_DESC_LENGTH",MQ_AUTH_INFO_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTH_INFO_NAME_LENGTH",MQ_AUTH_INFO_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTHENTICATOR_LENGTH",MQ_AUTO_REORG_CATALOG_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTO_REORG_CATALOG_LENGTH",MQ_AUTO_REORG_CATALOG_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_AUTO_REORG_TIME_LENGTH",MQ_AUTO_REORG_TIME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_BATCH_INTERFACE_ID_LENGTH",MQ_BATCH_INTERFACE_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_BRIDGE_NAME_LENGTH",MQ_BRIDGE_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CANCEL_CODE_LENGTH",MQ_CANCEL_CODE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CF_STRUC_DESC_LENGTH",MQ_CF_STRUC_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CF_STRUC_NAME_LENGTH",MQ_CF_STRUC_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CHANNEL_DATE_LENGTH",MQ_CHANNEL_DATE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CHANNEL_DESC_LENGTH",MQ_CHANNEL_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CHANNEL_NAME_LENGTH",MQ_CHANNEL_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CHANNEL_TIME_LENGTH",MQ_CHANNEL_TIME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CHINIT_SERVICE_PARM_LENGTH",MQ_CHINIT_SERVICE_PARM_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CICS_FILE_NAME_LENGTH",MQ_CICS_FILE_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CLUSTER_NAME_LENGTH",MQ_CLUSTER_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CONN_NAME_LENGTH",MQ_CONN_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CONN_TAG_LENGTH",MQ_CONNECTION_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CONNECTION_ID_LENGTH",MQ_CONNECTION_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CORREL_ID_LENGTH",MQ_CORREL_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CREATION_DATE_LENGTH",MQ_CREATION_DATE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_CREATION_TIME_LENGTH",MQ_CREATION_TIME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_DATE_LENGTH",MQ_DATE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_DISTINGUISHED_NAME_LENGTH",MQ_DISTINGUISHED_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_DNS_GROUP_NAME_LENGTH",MQ_DNS_GROUP_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_EXIT_DATA_LENGTH",MQ_EXIT_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_EXIT_INFO_NAME_LENGTH",MQ_EXIT_INFO_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_EXIT_NAME_LENGTH",MQ_EXIT_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_EXIT_PD_AREA_LENGTH",MQ_EXIT_PD_AREA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_EXIT_USER_AREA_LENGTH",MQ_EXIT_USER_AREA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_FACILITY_LENGTH",MQ_FACILITY_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_FACILITY_LIKE_LENGTH",MQ_FACILITY_LIKE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_FORMAT_LENGTH",MQ_FORMAT_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_FUNCTION_LENGTH",MQ_FUNCTION_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_GROUP_ID_LENGTH",MQ_GROUP_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LDAP_PASSWORD_LENGTH",MQ_LDAP_PASSWORD_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LISTENER_NAME_LENGTH",MQ_LISTENER_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LISTENER_DESC_LENGTH",MQ_LISTENER_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LOCAL_ADDRESS_LENGTH",MQ_LOCAL_ADDRESS_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LTERM_OVERRIDE_LENGTH",MQ_LTERM_OVERRIDE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LU_NAME_LENGTH",MQ_LU_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_LUWID_LENGTH",MQ_LUWID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MAX_EXIT_NAME_LENGTH",MQ_MAX_EXIT_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MAX_MCA_USER_ID_LENGTH",MQ_MAX_MCA_USER_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MAX_USER_ID_LENGTH",MQ_MAX_USER_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MCA_JOB_NAME_LENGTH",MQ_MCA_JOB_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MCA_NAME_LENGTH",MQ_MCA_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MCA_USER_DATA_LENGTH",MQ_MCA_USER_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MCA_USER_ID_LENGTH",MQ_MCA_USER_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MFS_MAP_NAME_LENGTH",MQ_MFS_MAP_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MODE_NAME_LENGTH",MQ_MODE_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MSG_HEADER_LENGTH",MQ_MSG_HEADER_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MSG_ID_LENGTH",MQ_MSG_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_MSG_TOKEN_LENGTH",MQ_MSG_TOKEN_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_NAMELIST_DESC_LENGTH",MQ_NAMELIST_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_NAMELIST_NAME_LENGTH",MQ_NAMELIST_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_OBJECT_INSTANCE_ID_LENGTH",MQ_OBJECT_INSTANCE_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_OBJECT_NAME_LENGTH",MQ_OBJECT_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PASS_TICKET_APPL_LENGTH",MQ_PASS_TICKET_APPL_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PASSWORD_LENGTH",MQ_PASSWORD_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROCESS_APPL_ID_LENGTH",MQ_PROCESS_APPL_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROCESS_DESC_LENGTH",MQ_PROCESS_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROCESS_ENV_DATA_LENGTH",MQ_PROCESS_ENV_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROCESS_NAME_LENGTH",MQ_PROCESS_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROCESS_USER_DATA_LENGTH",MQ_PROCESS_USER_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PROGRAM_NAME_LENGTH",MQ_PROGRAM_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PUT_APPL_NAME_LENGTH",MQ_PUT_APPL_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PUT_DATE_LENGTH",MQ_PUT_DATE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_PUT_TIME_LENGTH",MQ_PUT_TIME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_Q_DESC_LENGTH",MQ_Q_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_Q_MGR_DESC_LENGTH",MQ_Q_MGR_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_Q_MGR_IDENTIFIER_LENGTH",MQ_Q_MGR_IDENTIFIER_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_Q_MGR_NAME_LENGTH",MQ_Q_MGR_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_Q_NAME_LENGTH",MQ_Q_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_QSG_NAME_LENGTH",MQ_QSG_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_REMOTE_SYS_ID_LENGTH",MQ_REMOTE_SYS_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SECURITY_ID_LENGTH",MQ_SECURITY_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_ARGS_LENGTH",MQ_SERVICE_ARGS_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_COMMAND_LENGTH",MQ_SERVICE_COMMAND_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_DESC_LENGTH",MQ_SERVICE_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_NAME_LENGTH",MQ_SERVICE_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_PATH_LENGTH",MQ_SERVICE_PATH_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SERVICE_STEP_LENGTH",MQ_SERVICE_STEP_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SHORT_CONN_NAME_LENGTH",MQ_SHORT_CONN_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SHORT_DNAME_LENGTH",MQ_SHORT_DNAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_CIPHER_SPEC_LENGTH",MQ_SSL_CIPHER_SPEC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_CRYPTO_HARDWARE_LENGTH",MQ_SSL_CRYPTO_HARDWARE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_HANDSHAKE_STAGE_LENGTH",MQ_SSL_HANDSHAKE_STAGE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_KEY_LIBRARY_LENGTH",MQ_SSL_KEY_LIBRARY_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_KEY_MEMBER_LENGTH",MQ_SSL_KEY_MEMBER_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_KEY_REPOSITORY_LENGTH",MQ_SSL_KEY_REPOSITORY_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_PEER_NAME_LENGTH",MQ_SSL_PEER_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SSL_SHORT_PEER_NAME_LENGTH",MQ_SSL_SHORT_PEER_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_START_CODE_LENGTH",MQ_START_CODE_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_STORAGE_CLASS_DESC_LENGTH",MQ_STORAGE_CLASS_DESC_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_STORAGE_CLASS_LENGTH",MQ_STORAGE_CLASS_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_SUB_IDENTITY_LENGTH",MQ_SUB_IDENTITY_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TCP_NAME_LENGTH",MQ_TCP_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TIME_LENGTH",MQ_TIME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TOTAL_EXIT_DATA_LENGTH",MQ_TOTAL_EXIT_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TOTAL_EXIT_NAME_LENGTH",MQ_TOTAL_EXIT_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TP_NAME_LENGTH",MQ_TP_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TPIPE_NAME_LENGTH",MQ_TPIPE_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRAN_INSTANCE_ID_LENGTH",MQ_TRAN_INSTANCE_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRANSACTION_ID_LENGTH",MQ_TRANSACTION_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRIGGER_DATA_LENGTH",MQ_TRIGGER_DATA_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRIGGER_PROGRAM_NAME_LENGTH",MQ_TRIGGER_PROGRAM_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRIGGER_TERM_ID_LENGTH",MQ_TRIGGER_TRANS_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_TRIGGER_TRANS_ID_LENGTH",MQ_TRIGGER_TRANS_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_USER_ID_LENGTH",MQ_USER_ID_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_XCF_GROUP_NAME_LENGTH",MQ_XCF_GROUP_NAME_LENGTH, CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MQSERIES_MQ_XCF_MEMBER_NAME_LENGTH",MQ_XCF_MEMBER_NAME_LENGTH, CONST_PERSISTENT);

